# Generated by Django 5.0 on 2026-05-11 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroad_frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecontent',
            name='pricing_heading_ar',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='pricing_heading_en',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='pricing_kicker_ar',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='homepagecontent',
            name='pricing_kicker_en',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
