# Generated by Django 5.0 on 2026-05-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroad_frontend', '0002_pricing_section_headers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepagecontent',
            name='pricing_heading_en',
            field=models.CharField(blank=True, default='Pricing that scales with your transport team', max_length=300),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='pricing_kicker_en',
            field=models.CharField(blank=True, default='Pricing Plans', max_length=200),
        ),
    ]
