# Generated by Django 5.0 on 2026-05-11 12:33

import django.core.validators
import iroad_frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroad_frontend', '0003_pricing_header_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homemaplocation',
            name='card_image',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='about_experience_image',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='about_main_image',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='about_point_1_icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='about_point_2_icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='business_map_image',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='business_side_image',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='favicon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_a_icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_a_image',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_b_icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_c_icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_c_image',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='feature_d_icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_image_primary',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='hero_image_secondary',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='logo_image',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='testimonials_hero_image',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='why_image_1',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='why_image_2',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='why_image_3',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='why_point_1_icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='why_point_2_icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homepagecontent',
            name='why_point_3_icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='homeservicecard',
            name='icon',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='hometestimonial',
            name='author_avatar',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='hometestimonial',
            name='company_logo',
            field=models.FileField(blank=True, null=True, upload_to=iroad_frontend.models.home_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])]),
        ),
    ]
