# Generated by Django 5.0 on 2026-05-12 07:14

import iroad_frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroad_frontend', '0009_remove_home_marketing_faq_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title_en', models.CharField(blank=True, default='Contact IRoad', max_length=200)),
                ('page_title_ar', models.CharField(blank=True, default='تواصل مع آيروود', max_length=200)),
                ('meta_description_en', models.TextField(blank=True, default='')),
                ('meta_description_ar', models.TextField(blank=True, default='')),
                ('page_header_h1_en', models.CharField(blank=True, default='Contact IRoad', max_length=300)),
                ('page_header_h1_ar', models.CharField(blank=True, default='تواصل مع آيروود', max_length=300)),
                ('breadcrumb_current_en', models.CharField(blank=True, default='Contact', max_length=100)),
                ('breadcrumb_current_ar', models.CharField(blank=True, default='تواصل', max_length=100)),
                ('section_kicker_en', models.CharField(blank=True, default='contact Us', max_length=200)),
                ('section_kicker_ar', models.CharField(blank=True, default='تواصل معنا', max_length=200)),
                ('section_heading_en', models.CharField(blank=True, default='Get in touch with our team to explore IRoad', max_length=300)),
                ('section_heading_ar', models.CharField(blank=True, default='', max_length=300)),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to=iroad_frontend.models.contact_upload_path)),
                ('form_title_en', models.CharField(blank=True, default='Request a Demo', max_length=200)),
                ('form_title_ar', models.CharField(blank=True, default='اطلب عرضاً', max_length=200)),
                ('form_fname_placeholder_en', models.CharField(blank=True, default='First Name', max_length=100)),
                ('form_fname_placeholder_ar', models.CharField(blank=True, default='الاسم الأول', max_length=100)),
                ('form_lname_placeholder_en', models.CharField(blank=True, default='Last Name', max_length=100)),
                ('form_lname_placeholder_ar', models.CharField(blank=True, default='اسم العائلة', max_length=100)),
                ('form_phone_placeholder_en', models.CharField(blank=True, default='Phone Number', max_length=100)),
                ('form_phone_placeholder_ar', models.CharField(blank=True, default='رقم الهاتف', max_length=100)),
                ('form_email_placeholder_en', models.CharField(blank=True, default='Email Address', max_length=100)),
                ('form_email_placeholder_ar', models.CharField(blank=True, default='البريد الإلكتروني', max_length=100)),
                ('form_message_placeholder_en', models.TextField(blank=True, default='Tell us about your transport business or requirements')),
                ('form_message_placeholder_ar', models.TextField(blank=True, default='أخبرنا عن متطلباتك')),
                ('form_consent_label_en', models.CharField(blank=True, default='I agree to receive communication regarding product updates and demo scheduling.', max_length=500)),
                ('form_consent_label_ar', models.CharField(blank=True, default='', max_length=500)),
                ('form_submit_label_en', models.CharField(blank=True, default='Book Demo', max_length=100)),
                ('form_submit_label_ar', models.CharField(blank=True, default='احجز عرضاً', max_length=100)),
                ('form_action_url', models.CharField(blank=True, default='/contact/submit/', max_length=500)),
                ('sidebar_heading_en', models.CharField(blank=True, default='Start your digital transport journey with IRoad', max_length=300)),
                ('sidebar_heading_ar', models.CharField(blank=True, default='', max_length=300)),
                ('support_label_en', models.CharField(blank=True, default='Our Support', max_length=100)),
                ('support_label_ar', models.CharField(blank=True, default='الدعم', max_length=100)),
                ('support_hours_en', models.CharField(blank=True, default='Monday - Friday : 9:00 AM - 6:00 PM', max_length=200)),
                ('support_hours_ar', models.CharField(blank=True, default='', max_length=200)),
                ('support_online_label_en', models.CharField(blank=True, default='24/7 Email Support Available', max_length=200)),
                ('support_online_label_ar', models.CharField(blank=True, default='', max_length=200)),
                ('info_book_label_en', models.CharField(blank=True, default='Book a Demo', max_length=100)),
                ('info_book_label_ar', models.CharField(blank=True, default='احجز عرضاً', max_length=100)),
                ('info_phone_1', models.CharField(blank=True, default='+91 98765 43210', max_length=50)),
                ('info_phone_2', models.CharField(blank=True, default='+91 91234 56789', max_length=50)),
                ('info_email_label_en', models.CharField(blank=True, default='Email', max_length=100)),
                ('info_email_label_ar', models.CharField(blank=True, default='البريد', max_length=100)),
                ('info_email_1', models.CharField(blank=True, default='support@iroad.com', max_length=200)),
                ('info_email_2', models.CharField(blank=True, default='sales@iroad.com', max_length=200)),
                ('info_platform_label_en', models.CharField(blank=True, default='Cloud-Based Platform - Accessible Worldwide', max_length=200)),
                ('info_platform_label_ar', models.CharField(blank=True, default='', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Contact Page Content',
                'verbose_name_plural': 'Contact Page Content',
                'db_table': 'iroad_frontend_contact_content',
            },
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('consent_given', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'db_table': 'iroad_frontend_contact_submission',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
