# Generated by Django 5.0 on 2026-05-12 07:32

import django.core.validators
import iroad_frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroad_frontend', '0010_contact_page_cms'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagecontent',
            name='page_header_background',
            field=models.FileField(blank=True, help_text='Optional hero background for the contact page header. If empty, a solid theme fallback is used (no stock photo).', null=True, upload_to=iroad_frontend.models.contact_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])], verbose_name='Page header background image'),
        ),
    ]
