# Generated by Django 5.0 on 2026-05-12 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroad_frontend', '0011_contact_page_header_background'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingFaqItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('question_en', models.CharField(blank=True, default='', max_length=500)),
                ('question_ar', models.CharField(blank=True, default='', max_length=500)),
                ('answer_en', models.TextField(blank=True, default='')),
                ('answer_ar', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faq_items', to='iroad_frontend.pricingpagecontent')),
            ],
            options={
                'verbose_name': 'Pricing FAQ Item',
                'verbose_name_plural': 'Pricing FAQ Items',
                'db_table': 'iroad_frontend_pricing_faq_item',
                'ordering': ['order'],
            },
        ),
    ]
