# Generated by Django 5.0 on 2026-05-13 05:41

import django.core.validators
import iroad_frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroad_frontend', '0014_pricing_partner_email_label_ar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicyPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title_en', models.CharField(blank=True, default='Privacy Policy - IRoad', max_length=200)),
                ('page_title_ar', models.CharField(blank=True, default='سياسة الخصوصية - آيروود', max_length=200)),
                ('meta_description_en', models.TextField(blank=True, default='')),
                ('meta_description_ar', models.TextField(blank=True, default='')),
                ('page_header_h1_en', models.CharField(blank=True, default='Privacy Policy', max_length=300)),
                ('page_header_h1_ar', models.CharField(blank=True, default='سياسة الخصوصية', max_length=300)),
                ('breadcrumb_current_en', models.CharField(blank=True, default='Privacy Policy', max_length=100)),
                ('breadcrumb_current_ar', models.CharField(blank=True, default='سياسة الخصوصية', max_length=100)),
                ('page_header_background', models.FileField(blank=True, help_text='Optional hero background for the privacy policy page header. If empty, a solid theme fallback is used.', null=True, upload_to=iroad_frontend.models.privacy_policy_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])], verbose_name='Page header background image')),
                ('content_en', models.TextField(blank=True, default='')),
                ('content_ar', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Privacy Policy Page Content',
                'verbose_name_plural': 'Privacy Policy Page Content',
                'db_table': 'iroad_frontend_privacy_policy_content',
            },
        ),
        migrations.CreateModel(
            name='TermsConditionsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title_en', models.CharField(blank=True, default='Terms & Conditions - IRoad', max_length=200)),
                ('page_title_ar', models.CharField(blank=True, default='الشروط والأحكام - آيروود', max_length=200)),
                ('meta_description_en', models.TextField(blank=True, default='')),
                ('meta_description_ar', models.TextField(blank=True, default='')),
                ('page_header_h1_en', models.CharField(blank=True, default='Terms & Conditions', max_length=300)),
                ('page_header_h1_ar', models.CharField(blank=True, default='الشروط والأحكام', max_length=300)),
                ('breadcrumb_current_en', models.CharField(blank=True, default='Terms & Conditions', max_length=100)),
                ('breadcrumb_current_ar', models.CharField(blank=True, default='الشروط والأحكام', max_length=100)),
                ('page_header_background', models.FileField(blank=True, help_text='Optional hero background for the terms page header. If empty, a solid theme fallback is used.', null=True, upload_to=iroad_frontend.models.terms_conditions_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])], verbose_name='Page header background image')),
                ('content_en', models.TextField(blank=True, default='')),
                ('content_ar', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Terms & Conditions Page Content',
                'verbose_name_plural': 'Terms & Conditions Page Content',
                'db_table': 'iroad_frontend_terms_conditions_content',
            },
        ),
    ]
