# Generated by Django 5.0 on 2026-05-14 05:48

import django.core.validators
import iroad_frontend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iroad_frontend', '0015_legal_page_cms_singletons'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileAboutUsPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title_en', models.CharField(blank=True, default='About Us - IRoad', max_length=200)),
                ('page_title_ar', models.CharField(blank=True, default='من نحن - آيروود', max_length=200)),
                ('meta_description_en', models.TextField(blank=True, default='')),
                ('meta_description_ar', models.TextField(blank=True, default='')),
                ('page_header_h1_en', models.CharField(blank=True, default='About Us', max_length=300)),
                ('page_header_h1_ar', models.CharField(blank=True, default='من نحن', max_length=300)),
                ('breadcrumb_current_en', models.CharField(blank=True, default='About Us', max_length=100)),
                ('breadcrumb_current_ar', models.CharField(blank=True, default='من نحن', max_length=100)),
                ('page_header_background', models.FileField(blank=True, help_text='Optional hero background for the mobile About Us page header. If empty, a solid theme fallback is used.', null=True, upload_to=iroad_frontend.models.mobile_about_us_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'gif', 'webp', 'ico', 'bmp', 'avif', 'tif', 'tiff'])], verbose_name='Page header background image')),
                ('content_en', models.TextField(blank=True, default='')),
                ('content_ar', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'Mobile About Us Page Content',
                'verbose_name_plural': 'Mobile About Us Page Content',
                'db_table': 'iroad_frontend_mobile_about_us_content',
            },
        ),
    ]
