# Generated by Django 5.0 on 2026-04-23 07:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0003_remove_autonumberconfiguration_next_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_code', models.CharField(max_length=100, unique=True)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_auto_number_sequence',
            },
        ),
        migrations.CreateModel(
            name='OrganizationProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_ref_no', models.CharField(max_length=64, unique=True)),
                ('account_sequence', models.PositiveIntegerField(default=1)),
                ('name_ar', models.CharField(blank=True, default='', max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('cr_number', models.CharField(blank=True, default='', max_length=50)),
                ('tax_number', models.CharField(blank=True, default='', max_length=50)),
                ('owner_user_id', models.CharField(blank=True, default='', max_length=64)),
                ('logo_file', models.ImageField(blank=True, null=True, upload_to='tenant/organization_logos/')),
                ('country_code', models.CharField(blank=True, default='', max_length=10)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('district', models.CharField(blank=True, default='', max_length=100)),
                ('street', models.CharField(blank=True, default='', max_length=150)),
                ('building_no', models.CharField(blank=True, default='', max_length=50)),
                ('postal_code', models.CharField(blank=True, default='', max_length=50)),
                ('address_line_1', models.CharField(blank=True, default='', max_length=255)),
                ('address_line_2', models.CharField(blank=True, default='', max_length=255)),
                ('primary_email', models.EmailField(blank=True, default='', max_length=150)),
                ('primary_mobile', models.CharField(blank=True, default='', max_length=30)),
                ('website', models.URLField(blank=True, default='', max_length=255)),
                ('base_currency_code', models.CharField(blank=True, default='', max_length=10)),
                ('system_language', models.CharField(choices=[('ar', 'Arabic'), ('en', 'English')], default='en', max_length=5)),
                ('timezone', models.CharField(default='Asia/Riyadh', max_length=64)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20)),
                ('number_format', models.CharField(choices=[('1,234.56', '1,234.56 (Standard)'), ('1.234,56', '1.234,56 (EU)')], default='1,234.56', max_length=20)),
                ('negative_format', models.CharField(choices=[('-100', '-100'), ('(100)', '(100)')], default='-100', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_organization_profile',
            },
        ),
    ]
