# Generated by Django 5.0 on 2026-05-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0013_sync_address_model_state'),
        ('tenant_workspace', '0015_tenantclientcontractsetting'),
    ]

    operations = [
    ]
