# Generated by Django 5.0 on 2026-05-03

import uuid
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_currency_country'),
        ('tenant_workspace', '0019_alter_tenantcargocategory_category_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantLocationMaster',
            fields=[
                ('location_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_code', models.CharField(max_length=64, unique=True)),
                ('location_sequence', models.PositiveIntegerField(default=0)),
                ('province', models.CharField(blank=True, default='', max_length=120)),
                ('location_name_arabic', models.CharField(blank=True, default='', max_length=200)),
                ('location_name_english', models.CharField(blank=True, default='', max_length=200)),
                ('display_label', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('City', 'City'), ('Area', 'Area'), ('Other', 'Other')], default='City', max_length=16)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=12)),
                ('is_serviceable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenant_locations', to='superadmin.country')),
            ],
            options={
                'db_table': 'tenant_location_master',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('country', 'province', 'display_label'), name='tenant_location_country_province_label_uq')],
            },
        ),
    ]

