# Generated by Django 5.0 on 2026-05-04 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0022_tenant_route_master_unique_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantServiceItemMaster',
            fields=[
                ('service_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_code', models.CharField(max_length=64, unique=True)),
                ('service_sequence', models.PositiveIntegerField(default=0)),
                ('service_type', models.CharField(choices=[('Service', 'Service'), ('Trip', 'Trip')], max_length=12)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=12)),
                ('english_name', models.CharField(max_length=200)),
                ('arabic_name', models.CharField(blank=True, default='', max_length=200)),
                ('category_name', models.CharField(max_length=200)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('outbound_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('inbound_sell_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_items', to='tenant_workspace.tenantroutemaster')),
            ],
            options={
                'db_table': 'tenant_service_item_master',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['service_type', 'status'], name='svc_item_type_status_idx')],
            },
        ),
    ]
