# Generated by Django 5.0 on 2026-05-04 12:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0023_tenantserviceitemmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantPriceList',
            fields=[
                ('price_list_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_list_code', models.CharField(max_length=64, unique=True)),
                ('price_list_sequence', models.PositiveIntegerField(default=0)),
                ('price_list_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Draft', max_length=12)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('base_currency', models.CharField(blank=True, default='', max_length=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_lists', to='tenant_workspace.tenantclientaccount')),
            ],
            options={
                'db_table': 'tenant_price_list',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['client_account', 'status'], name='price_list_client_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantPriceListTripLine',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trip_type', models.CharField(choices=[('One-Way', 'One-Way'), ('Round', 'Round')], max_length=12)),
                ('sell_price_override', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buy_price_override', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_lines', to='tenant_workspace.tenantpricelist')),
                ('trip_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_trip_lines', to='tenant_workspace.tenantserviceitemmaster')),
            ],
            options={
                'db_table': 'tenant_price_list_trip_line',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantPriceListServiceLine',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sell_price_override', models.DecimalField(decimal_places=2, max_digits=14)),
                ('buy_price_override', models.DecimalField(decimal_places=2, max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_lines', to='tenant_workspace.tenantpricelist')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='price_list_service_lines', to='tenant_workspace.tenantserviceitemmaster')),
            ],
            options={
                'db_table': 'tenant_price_list_service_line',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='tenantpricelist',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'Active')), fields=('client_account',), name='tenant_price_list_one_active_per_client_uq'),
        ),
        migrations.AddConstraint(
            model_name='tenantpricelisttripline',
            constraint=models.UniqueConstraint(fields=('price_list', 'trip_service', 'trip_type'), name='tenant_price_list_trip_line_uq'),
        ),
        migrations.AddConstraint(
            model_name='tenantpricelistserviceline',
            constraint=models.UniqueConstraint(fields=('price_list', 'service_item'), name='tenant_price_list_service_line_uq'),
        ),
    ]
