# Generated by Django 5.0 on 2026-05-05 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0023_remove_tenantaddressmaster_extension'),
        ('tenant_workspace', '0024_tenantpricelist_and_lines'),
    ]

    operations = [
    ]
