# Generated by Django 5.0 on 2026-05-05 05:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0025_merge_20260505_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckTypeMaster',
            fields=[
                ('truck_type_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('truck_type_code', models.CharField(max_length=64, unique=True)),
                ('truck_type_sequence', models.PositiveIntegerField(default=0)),
                ('english_label', models.CharField(max_length=200)),
                ('arabic_label', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Truck Type',
                'verbose_name_plural': 'Truck Types',
                'db_table': 'tenant_truck_type_master',
                'ordering': ['english_label'],
            },
        ),
    ]
