# Generated by Django 5.0 on 2026-05-05 05:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0034_refresh_tenant_welcome_email_template'),
        ('tenant_workspace', '0026_trucktypemaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckMaster',
            fields=[
                ('truck_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('truck_code', models.CharField(max_length=64, unique=True)),
                ('truck_sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=12)),
                ('sourcing_mode', models.CharField(choices=[('In-Source', 'In-Source'), ('Out-Source', 'Out-Source')], max_length=20)),
                ('vendor_account_id', models.CharField(blank=True, default='', max_length=64)),
                ('is_vendor_same_as_owner', models.BooleanField(default=False)),
                ('owner_id', models.CharField(blank=True, default='', max_length=100)),
                ('owner_name', models.CharField(blank=True, default='', max_length=200)),
                ('plate_number', models.CharField(max_length=100)),
                ('saudi_plate_number', models.CharField(blank=True, default='', max_length=50)),
                ('saudi_english_letters', models.CharField(blank=True, default='', max_length=10)),
                ('saudi_arabic_letters', models.CharField(blank=True, default='', max_length=10)),
                ('non_saudi_plate_number', models.CharField(blank=True, default='', max_length=100)),
                ('plate_image', models.ImageField(blank=True, null=True, upload_to='trucks/plates/')),
                ('chassis_number_vin', models.CharField(blank=True, default='', max_length=100)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('color', models.CharField(blank=True, default='', max_length=50)),
                ('vehicle_registration_image', models.ImageField(blank=True, null=True, upload_to='trucks/registration/')),
                ('axle_count', models.PositiveIntegerField(blank=True, null=True)),
                ('tires_count', models.PositiveIntegerField(blank=True, null=True)),
                ('tare_weight_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('payload_capacity_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('gross_weight_ton', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('default_driver_id', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registration_country', models.ForeignKey(db_column='registration_country_id', db_constraint=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='superadmin.country')),
                ('truck_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trucks', to='tenant_workspace.trucktypemaster')),
            ],
            options={
                'verbose_name': 'Truck',
                'verbose_name_plural': 'Trucks',
                'db_table': 'tenant_truck_master',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['truck_code', 'status'], name='tenant_truck_code_status_idx'), models.Index(fields=['registration_country', 'plate_number'], name='tenant_truck_reg_plate_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='truckmaster',
            constraint=models.UniqueConstraint(fields=('registration_country', 'plate_number'), name='tenant_truck_regcountry_plate_uniq'),
        ),
    ]
