# Generated by Django 5.0 on 2026-05-05 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0025_merge_20260504_2016'),
        ('tenant_workspace', '0030_truckattachment_require_file_notes'),
    ]

    operations = [
    ]
