# Generated by Django 5.0 on 2026-05-05 12:53

import tenant_workspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0032_truckattachment_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckattachment',
            name='attachment_file',
            field=models.FileField(max_length=500, upload_to=tenant_workspace.models.truck_attachment_upload_to),
        ),
    ]
