# Generated by Django 5.0 on 2026-05-06 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0031_merge_20260505_1532'),
        ('tenant_workspace', '0033_alter_truckattachment_attachment_file'),
    ]

    operations = [
    ]
