# Generated by Django 5.0 on 2026-05-06 05:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0035_alter_eventmapping_system_event_and_more'),
        ('tenant_workspace', '0033_alter_truckattachment_attachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverMaster',
            fields=[
                ('driver_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('driver_code', models.CharField(max_length=64, unique=True)),
                ('driver_sequence', models.PositiveIntegerField(default=0)),
                ('user_account_id', models.CharField(blank=True, default='', help_text='TODO: Replace with FK to UserAccount', max_length=100)),
                ('driver_source', models.CharField(choices=[('In-Source', 'In-Source'), ('Out-Source', 'Out-Source')], default='In-Source', max_length=20)),
                ('vendor_account_id', models.CharField(blank=True, default='', help_text='TODO: Replace with FK to VendorAccount', max_length=100)),
                ('driver_status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=12)),
                ('driver_type', models.CharField(blank=True, choices=[('Company', 'Company'), ('Vendor', 'Vendor'), ('Other', 'Other')], default='', max_length=20)),
                ('arabic_name', models.CharField(max_length=200)),
                ('english_name', models.CharField(blank=True, default='', max_length=200)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(blank=True, default='', max_length=50)),
                ('id_expiry_date', models.DateField(blank=True, null=True)),
                ('id_image', models.FileField(blank=True, max_length=500, null=True, upload_to='drivers/id/')),
                ('passport_number', models.CharField(blank=True, default='', max_length=50)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('passport_image', models.FileField(blank=True, max_length=500, null=True, upload_to='drivers/passport/')),
                ('dl_number', models.CharField(blank=True, default='', max_length=50)),
                ('dl_expiry_date', models.DateField(blank=True, null=True)),
                ('dl_image', models.FileField(blank=True, max_length=500, null=True, upload_to='drivers/license/')),
                ('card_number', models.CharField(blank=True, default='', max_length=50)),
                ('card_expiry_date', models.DateField(blank=True, null=True)),
                ('card_image', models.FileField(blank=True, max_length=500, null=True, upload_to='drivers/card/')),
                ('mobile_number', models.CharField(max_length=30)),
                ('whatsapp_number', models.CharField(blank=True, default='', max_length=30)),
                ('whatsapp_same_as_mobile', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nationality_country', models.ForeignKey(blank=True, db_column='nationality_country_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='superadmin.country')),
            ],
            options={
                'verbose_name': 'Driver',
                'verbose_name_plural': 'Drivers',
                'db_table': 'tenant_driver_master',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['driver_status'], name='tenant_driver_status_idx'), models.Index(fields=['driver_code'], name='tenant_driver_code_idx')],
            },
        ),
    ]
