# Generated by Django 5.0 on 2026-05-06 12:32

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0034_merge_20260506_0935'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantShipment',
            fields=[
                ('shipment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shipment_no', models.CharField(max_length=64, unique=True)),
                ('shipment_sequence', models.PositiveIntegerField(default=0)),
                ('shipment_date', models.DateField(default=datetime.date.today)),
                ('shipment_status', models.CharField(choices=[('Created', 'Created'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Closed', 'Closed'), ('Cancelled', 'Cancelled')], default='Created', max_length=20)),
                ('booking_no', models.CharField(max_length=64)),
                ('booking_item_ref', models.CharField(max_length=64)),
                ('booking_item_type', models.CharField(blank=True, default='', max_length=20)),
                ('sourcing_mode', models.CharField(choices=[('In-Source', 'In-Source'), ('Out-Source', 'Out-Source')], max_length=20)),
                ('trip_type', models.CharField(blank=True, default='', max_length=20)),
                ('route_display', models.CharField(blank=True, default='', max_length=120)),
                ('order_type', models.CharField(blank=True, default='', max_length=20)),
                ('from_location', models.CharField(blank=True, default='', max_length=120)),
                ('to_location', models.CharField(blank=True, default='', max_length=120)),
                ('client_account_ref', models.CharField(blank=True, default='', max_length=64)),
                ('sales_order_ref', models.CharField(blank=True, default='', max_length=64)),
                ('sales_order_item_ref', models.CharField(blank=True, default='', max_length=64)),
                ('vendor_account_ref', models.CharField(blank=True, default='', max_length=64)),
                ('purchase_order_ref', models.CharField(blank=True, default='', max_length=64)),
                ('purchase_order_item_ref', models.CharField(blank=True, default='', max_length=64)),
                ('driver_ref', models.CharField(blank=True, default='', max_length=64)),
                ('pod_type', models.CharField(choices=[('Digital', 'Digital'), ('Soft', 'Soft'), ('Hard', 'Hard')], default='Digital', max_length=12)),
                ('pod_status', models.CharField(choices=[('Compliant', 'Compliant'), ('Not Compliant', 'Not Compliant')], default='Not Compliant', max_length=20)),
                ('pod_doc_count', models.PositiveIntegerField(default=0)),
                ('cod_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('collection_status', models.CharField(choices=[('Pending', 'Pending'), ('Collected', 'Collected')], default='Pending', max_length=20)),
                ('sales_invoice_ref', models.CharField(blank=True, default='', max_length=64)),
                ('sales_invoice_status', models.CharField(blank=True, default='', max_length=32)),
                ('purchase_invoice_ref', models.CharField(blank=True, default='', max_length=64)),
                ('purchase_invoice_status', models.CharField(blank=True, default='', max_length=32)),
                ('created_by_label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shipments', to='tenant_workspace.truckmaster')),
            ],
            options={
                'db_table': 'tenant_shipments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantShipmentSurcharge',
            fields=[
                ('surcharge_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('item_label', models.CharField(max_length=120)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharges', to='tenant_workspace.tenantshipment')),
            ],
            options={
                'db_table': 'tenant_shipment_surcharges',
                'ordering': ['line_no', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='tenantshipment',
            index=models.Index(fields=['booking_no', 'booking_item_ref'], name='tenant_shipment_booking_idx'),
        ),
        migrations.AddIndex(
            model_name='tenantshipment',
            index=models.Index(fields=['shipment_status'], name='tenant_shipment_status_idx'),
        ),
    ]
