# Generated by Django 5.0 on 2026-05-06 05:36

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0034_drivermaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverSettings',
            fields=[
                ('settings_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('default_driver_status', models.CharField(choices=[('Active', 'Active'), ('Suspended', 'Suspended'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('notification_audience', models.CharField(choices=[('System Admin', 'System Admin'), ('Fleet Manager', 'Fleet Manager'), ('Both', 'Both')], default='System Admin', max_length=30)),
                ('license_expiry_alert_days', models.PositiveIntegerField(default=30)),
                ('document_expiry_alert_days', models.PositiveIntegerField(default=30)),
                ('medical_expiry_alert_days', models.PositiveIntegerField(default=30)),
                ('driver_assignment_required', models.BooleanField(default=False)),
                ('document_upload_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver Settings',
                'verbose_name_plural': 'Driver Settings',
                'db_table': 'tenant_driver_settings',
            },
        ),
        migrations.CreateModel(
            name='DriverAttachment',
            fields=[
                ('attachment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attachment_date', models.DateField(default=datetime.date.today)),
                ('is_expiry_applicable', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('attachment_file', models.FileField(max_length=500, upload_to='drivers/attachments/')),
                ('file_notes', models.TextField(help_text='Describe this document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tenant_workspace.drivermaster')),
            ],
            options={
                'verbose_name': 'Driver Attachment',
                'verbose_name_plural': 'Driver Attachments',
                'db_table': 'tenant_driver_attachments',
                'ordering': ['-attachment_date', '-created_at'],
            },
        ),
    ]
