# Generated by Django 5.0 on 2026-05-06 13:05

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0035_tenantshipment_tenantshipmentsurcharge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantShipmentDocument',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_no', models.CharField(max_length=64, unique=True)),
                ('record_sequence', models.PositiveIntegerField(default=0)),
                ('record_date', models.DateField(default=datetime.date.today)),
                ('booking_no', models.CharField(max_length=64)),
                ('booking_item', models.CharField(max_length=64)),
                ('shipment_ref', models.CharField(max_length=64)),
                ('document_type', models.CharField(max_length=64)),
                ('document_ref_no', models.CharField(max_length=120)),
                ('document_date', models.DateField(default=datetime.date.today)),
                ('is_delivery_note', models.BooleanField(default=False)),
                ('physical_location', models.CharField(blank=True, default='', max_length=255)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Draft', max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by_label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_shipment_documents',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['record_no'], name='tenant_shipdoc_record_idx'), models.Index(fields=['shipment_ref'], name='tenant_shipdoc_shipref_idx'), models.Index(fields=['status'], name='tenant_shipdoc_status_idx')],
            },
        ),
    ]
