# Generated by Django 5.0 on 2026-05-06 06:53

import tenant_workspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0035_driversettings_driverattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverattachment',
            name='arabic_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='driverattachment',
            name='attachment_no',
            field=models.CharField(blank=True, help_text='Auto-generated attachment number', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='driverattachment',
            name='attachment_sequence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driverattachment',
            name='doc_ref_number',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='driverattachment',
            name='english_label',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='driverattachment',
            name='attachment_file',
            field=models.FileField(max_length=500, upload_to=tenant_workspace.models.driver_attachment_upload_to),
        ),
    ]
