# Generated by Django 5.0 on 2026-05-07 10:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0036_tenantshipmentdocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantShipmentPodPage',
            fields=[
                ('page_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('doc_page', models.CharField(blank=True, default='', max_length=64)),
                ('source', models.CharField(blank=True, default='', max_length=64)),
                ('action_log', models.CharField(blank=True, default='', max_length=120)),
                ('physical_location', models.CharField(blank=True, default='', max_length=120)),
                ('soft_copy_status', models.CharField(blank=True, default='', max_length=64)),
                ('digital_evidence_status', models.CharField(blank=True, default='', max_length=64)),
                ('map_url', models.URLField(blank=True, default='')),
                ('attachment_label', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pod_pages', to='tenant_workspace.tenantshipmentdocument')),
            ],
            options={
                'db_table': 'tenant_shipment_pod_pages',
                'ordering': ['line_no', 'created_at'],
                'indexes': [models.Index(fields=['document', 'line_no'], name='tenant_podpage_doc_line_idx')],
            },
        ),
    ]
