# Generated by Django 5.0 on 2026-05-07 10:14

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0037_tenantshipmentpodpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantDocumentHandover',
            fields=[
                ('handover_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handover_no', models.CharField(max_length=64, unique=True)),
                ('handover_sequence', models.PositiveIntegerField(default=0)),
                ('handover_date', models.DateField(default=datetime.date.today)),
                ('booking_no', models.CharField(max_length=64)),
                ('booking_item', models.CharField(blank=True, default='', max_length=64)),
                ('shipment_ref', models.CharField(max_length=64)),
                ('document_ref', models.CharField(blank=True, default='', max_length=120)),
                ('pod_record_ref', models.CharField(blank=True, default='', max_length=120)),
                ('physical_location', models.CharField(blank=True, default='', max_length=120)),
                ('received_user', models.CharField(blank=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Posted', 'Posted'), ('Client Received', 'Client Received'), ('Rejected', 'Rejected'), ('Missing', 'Missing')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by_label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_document_handovers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['handover_no'], name='tenant_doc_ho_no_idx'), models.Index(fields=['shipment_ref'], name='tenant_doc_ho_ship_idx'), models.Index(fields=['status'], name='tenant_doc_ho_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantDocumentHandoverLine',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('doc_page', models.CharField(blank=True, default='', max_length=64)),
                ('page_status', models.CharField(blank=True, default='', max_length=64)),
                ('physical_location', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handover', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='tenant_workspace.tenantdocumenthandover')),
            ],
            options={
                'db_table': 'tenant_document_handover_lines',
                'ordering': ['line_no', 'created_at'],
                'indexes': [models.Index(fields=['handover', 'line_no'], name='tenant_doc_ho_line_idx')],
            },
        ),
    ]
