# Generated by Django 5.0 on 2026-05-07 10:41

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0038_tenantdocumenthandover_tenantdocumenthandoverline'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantTruckMovementLog',
            fields=[
                ('movement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_no', models.CharField(max_length=64, unique=True)),
                ('movement_sequence', models.PositiveIntegerField(default=0)),
                ('movement_date', models.DateField(default=datetime.date.today)),
                ('movement_source', models.CharField(blank=True, default='', max_length=32)),
                ('empty_move_reason', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('booking_ref', models.CharField(blank=True, default='', max_length=64)),
                ('shipment_ref', models.CharField(blank=True, default='', max_length=64)),
                ('truck_ref', models.CharField(blank=True, default='', max_length=120)),
                ('driver_ref', models.CharField(blank=True, default='', max_length=120)),
                ('from_location', models.CharField(blank=True, default='', max_length=120)),
                ('from_location_map_link', models.URLField(blank=True, default='')),
                ('to_location', models.CharField(blank=True, default='', max_length=120)),
                ('to_location_map_link', models.URLField(blank=True, default='')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_by_label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_truck_movement_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['movement_no'], name='tenant_tml_no_idx'), models.Index(fields=['status'], name='tenant_tml_status_idx')],
            },
        ),
    ]
