# Generated by Django 5.0 on 2026-05-07 11:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0039_tenanttruckmovementlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantOperationAction',
            fields=[
                ('action_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_code', models.CharField(max_length=64, unique=True)),
                ('arabic_label', models.CharField(blank=True, default='', max_length=200)),
                ('english_label', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=16)),
                ('action_scope', models.CharField(blank=True, default='', max_length=32)),
                ('sequence_category', models.CharField(blank=True, default='', max_length=64)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('auto_movement_post', models.BooleanField(default=False)),
                ('auto_shipment_post', models.BooleanField(default=False)),
                ('auto_pod_post', models.BooleanField(default=False)),
                ('hard_copy_collection', models.BooleanField(default=False)),
                ('booking_status_impact', models.CharField(blank=True, default='', max_length=64)),
                ('shipment_status_impact', models.CharField(blank=True, default='', max_length=64)),
                ('movement_status_impact', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenant_operation_actions',
                'ordering': ['action_code'],
                'indexes': [models.Index(fields=['action_code'], name='tenant_op_action_code_idx'), models.Index(fields=['status'], name='tenant_op_action_status_idx')],
            },
        ),
    ]
