# Generated by Django 5.0 on 2026-05-07 08:24

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0040_trucksettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceReport',
            fields=[
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('report_no', models.CharField(max_length=64, unique=True)),
                ('report_sequence', models.PositiveIntegerField(default=0)),
                ('report_date', models.DateField(default=django.utils.timezone.localdate)),
                ('booking_date_from', models.DateField()),
                ('booking_date_to', models.DateField()),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('total_freight_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_surcharge_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Verified', 'Verified'), ('Converted', 'Converted')], default='Draft', max_length=12)),
                ('sales_invoice_ref', models.UUIDField(blank=True, db_index=True, help_text='FK-ready reference to Sales Invoice (model pending).', null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('updated_by', models.CharField(blank=True, default='', max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_reports', to='tenant_workspace.tenantclientaccount')),
            ],
            options={
                'db_table': 'tenant_sales_invoice_report',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceReportBooking',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField()),
                ('booking_ref', models.UUIDField(blank=True, db_index=True, help_text='FK-ready reference to Booking (model pending).', null=True)),
                ('so_ref', models.CharField(blank=True, default='', max_length=120)),
                ('service_name', models.CharField(blank=True, default='', max_length=200)),
                ('trip_type', models.CharField(blank=True, default='', max_length=50)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('booking_status', models.CharField(blank=True, default='', help_text='Snapshot of booking execution status (expects Executed).', max_length=30)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_lines', to='tenant_workspace.salesinvoicereport')),
            ],
            options={
                'db_table': 'tenant_sales_invoice_report_booking',
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceReportShipment',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField()),
                ('shipment_ref', models.UUIDField(blank=True, db_index=True, help_text='FK-ready reference to Shipment (model pending).', null=True)),
                ('booking_ref', models.CharField(blank=True, default='', max_length=120)),
                ('shipment_date', models.DateField(blank=True, null=True)),
                ('from_location', models.CharField(blank=True, default='', max_length=200)),
                ('to_location', models.CharField(blank=True, default='', max_length=200)),
                ('truck_plate', models.CharField(blank=True, default='', max_length=120)),
                ('customer_ref_docs', models.TextField(blank=True, default='')),
                ('pod_date', models.DateField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipment_lines', to='tenant_workspace.salesinvoicereport')),
            ],
            options={
                'db_table': 'tenant_sales_invoice_report_shipment',
                'ordering': ['line_no'],
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceReportSurcharge',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('line_no', models.PositiveIntegerField()),
                ('surcharge_trx_ref', models.UUIDField(blank=True, db_index=True, help_text='FK-ready reference to Surcharge Sales Transaction (model pending).', null=True)),
                ('booking_ref', models.UUIDField(blank=True, db_index=True, help_text='FK-ready reference to Booking (model pending).', null=True)),
                ('surcharge_type', models.CharField(blank=True, default='', max_length=120)),
                ('shipment_ref', models.CharField(blank=True, default='', max_length=120)),
                ('service_name', models.CharField(blank=True, default='', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surcharge_lines', to='tenant_workspace.salesinvoicereport')),
            ],
            options={
                'db_table': 'tenant_sales_invoice_report_surcharge',
                'ordering': ['line_no'],
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoicereport',
            index=models.Index(fields=['report_no'], name='sir_report_no_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicereport',
            index=models.Index(fields=['client', 'status'], name='sir_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicereport',
            index=models.Index(fields=['booking_date_from', 'booking_date_to'], name='sir_booking_period_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicereportbooking',
            index=models.Index(fields=['report', 'line_no'], name='sir_booking_report_line_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicereportbooking',
            index=models.Index(fields=['booking_ref'], name='sir_booking_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicereportbooking',
            constraint=models.UniqueConstraint(fields=('report', 'line_no'), name='sir_booking_line_no_uq'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicereportbooking',
            constraint=models.UniqueConstraint(condition=models.Q(('booking_ref__isnull', False)), fields=('report', 'booking_ref'), name='sir_unique_booking_per_report_uq'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicereportshipment',
            index=models.Index(fields=['report', 'line_no'], name='sir_shipment_report_line_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicereportshipment',
            index=models.Index(fields=['shipment_ref'], name='sir_shipment_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicereportshipment',
            constraint=models.UniqueConstraint(fields=('report', 'line_no'), name='sir_shipment_line_no_uq'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicereportsurcharge',
            index=models.Index(fields=['report', 'line_no'], name='sir_surcharge_report_line_idx'),
        ),
        migrations.AddIndex(
            model_name='salesinvoicereportsurcharge',
            index=models.Index(fields=['surcharge_trx_ref'], name='sir_surcharge_trx_ref_idx'),
        ),
        migrations.AddConstraint(
            model_name='salesinvoicereportsurcharge',
            constraint=models.UniqueConstraint(fields=('report', 'line_no'), name='sir_surcharge_line_no_uq'),
        ),
    ]
