# Generated by Django 5.0 on 2026-05-07 11:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0041_salesinvoicereport_salesinvoicereportbooking_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverTreasury',
            fields=[
                ('treasury_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treasury_code', models.CharField(max_length=64, unique=True)),
                ('treasury_sequence', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='treasuries', to='tenant_workspace.drivermaster')),
            ],
            options={
                'verbose_name': 'Driver Treasury',
                'verbose_name_plural': 'Driver Treasuries',
                'db_table': 'tenant_driver_treasury',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DriverTreasuryTransaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(max_length=64, unique=True)),
                ('transaction_sequence', models.PositiveIntegerField(default=0)),
                ('transaction_date', models.DateTimeField()),
                ('transaction_type', models.CharField(choices=[('Credit', 'Credit'), ('Debit', 'Debit')], max_length=10)),
                ('transaction_category', models.CharField(choices=[('Client Collection', 'Client Collection'), ('Custody Collection', 'Custody Collection')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('related_shipment', models.CharField(blank=True, default='', help_text='TODO: FK to Shipment when module built', max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_treasury', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='tenant_workspace.drivertreasury')),
            ],
            options={
                'verbose_name': 'Driver Treasury Transaction',
                'verbose_name_plural': 'Driver Treasury Transactions',
                'db_table': 'tenant_driver_treasury_transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
