# Generated by Django 5.0 on 2026-05-07 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0040_tenantoperationaction'),
        ('tenant_workspace', '0041_salesinvoicereport_salesinvoicereportbooking_and_more'),
    ]

    operations = [
    ]
