# Generated by Django 5.0 on 2026-05-08 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0042_drivertreasury_drivertreasurytransaction'),
        ('tenant_workspace', '0042_merge_20260507_1812'),
    ]

    operations = [
    ]
