# Generated by Django 5.0 on 2026-05-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0043_merge_20260507_1858'),
        ('tenant_workspace', '0043_merge_20260508_1131'),
    ]

    operations = [
    ]
