# Generated by Django 5.0 on 2026-05-11 12:59

import tenant_workspace.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0044_merge_20260511_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermaster',
            name='card_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tenant_workspace.models.driver_card_upload_to),
        ),
        migrations.AlterField(
            model_name='drivermaster',
            name='dl_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tenant_workspace.models.driver_license_upload_to),
        ),
        migrations.AlterField(
            model_name='drivermaster',
            name='id_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tenant_workspace.models.driver_id_upload_to),
        ),
        migrations.AlterField(
            model_name='drivermaster',
            name='passport_image',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=tenant_workspace.models.driver_passport_upload_to),
        ),
        migrations.AlterField(
            model_name='organizationprofile',
            name='logo_file',
            field=models.ImageField(blank=True, null=True, upload_to=tenant_workspace.models.organization_logo_upload_to),
        ),
        migrations.AlterField(
            model_name='tenantcargomasterattachment',
            name='file',
            field=models.FileField(upload_to=tenant_workspace.models.cargo_master_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='tenantclientattachment',
            name='attachment_file',
            field=models.FileField(upload_to=tenant_workspace.models.client_attachment_upload_to),
        ),
        migrations.AlterField(
            model_name='tenantclientcontract',
            name='contract_attachment',
            field=models.FileField(upload_to=tenant_workspace.models.client_contract_upload_to),
        ),
        migrations.AlterField(
            model_name='truckimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=tenant_workspace.models.truck_image_upload_to),
        ),
        migrations.AlterField(
            model_name='truckmaster',
            name='plate_image',
            field=models.ImageField(blank=True, null=True, upload_to=tenant_workspace.models.truck_plate_image_upload_to),
        ),
        migrations.AlterField(
            model_name='truckmaster',
            name='vehicle_registration_image',
            field=models.ImageField(blank=True, null=True, upload_to=tenant_workspace.models.truck_registration_image_upload_to),
        ),
    ]
