# Generated by Django 5.0 on 2026-05-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0045_alter_drivermaster_card_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckmaster',
            name='operational_status',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Loaded', 'Loaded'), ('Suspended', 'Suspended')], default='', max_length=20, verbose_name='Operational status'),
        ),
    ]
