# Generated by Django 5.0 on 2026-05-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0046_truckmaster_operational_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truckmaster',
            name='is_vendor_same_as_owner',
            field=models.BooleanField(default=False, verbose_name='Is Company info as same Owner Info'),
        ),
    ]
