# Generated by Django 5.0 on 2026-05-13 07:44

import datetime
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0050_remove_driversettings_extra_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBooking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_no', models.CharField(max_length=64, unique=True)),
                ('booking_sequence', models.PositiveIntegerField(default=0)),
                ('creation_date', models.DateField(default=datetime.date.today)),
                ('booking_date', models.DateField(default=datetime.date.today)),
                ('execution_date', models.DateField(blank=True, null=True)),
                ('booking_status', models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('route_direction', models.CharField(blank=True, default='forward', max_length=12)),
                ('route_display', models.CharField(blank=True, default='', max_length=255)),
                ('order_type', models.CharField(blank=True, default='', max_length=20)),
                ('trip_type', models.CharField(blank=True, default='', max_length=20)),
                ('sell_price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('sourcing_mode', models.CharField(blank=True, default='', max_length=20)),
                ('pod_type', models.CharField(blank=True, default='', max_length=30)),
                ('pod_status', models.CharField(blank=True, default='', max_length=30)),
                ('created_by_label', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tenant_workspace.tenantclientaccount')),
                ('price_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tenant_workspace.tenantpricelist')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tenant_workspace.tenantroutemaster')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='tenant_workspace.tenantserviceitemmaster')),
            ],
            options={
                'db_table': 'tenant_bookings',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking_no'], name='tenant_booking_no_idx'), models.Index(fields=['client_account', 'booking_status'], name='tenant_bkg_client_status_idx')],
            },
        ),
    ]
