# Generated by Django 5.0 on 2026-05-13 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0050_remove_driversettings_extra_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='deleted_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_users_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
