# Generated by Django 5.0 on 2026-05-13 12:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0051_tenantuser_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'base_manager_name': 'all_objects', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelManagers(
            name='tenantuser',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
