# Generated by Django 5.0 on 2026-05-13 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0051_tenantbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbooking',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='tenant_workspace.drivermaster'),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='assigned_truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to='tenant_workspace.truckmaster'),
        ),
    ]
