# Generated by Django 5.0 on 2026-05-13 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0052_tenantbooking_assigned_driver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantbooking',
            name='booking_attachment',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='booking_attachments/'),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='booking_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='booking_line_cod_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='booking_line_pod_doc_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='tenant_workspace.tenantcargomaster'),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='cargo_booking_item',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='cargo_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='cargo_unit',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='cargo_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='container_no',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='total_cargo_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='tenantbooking',
            name='total_cargo_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
