# Generated by Django 5.0 on 2026-05-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0052_alter_tenantuser_options_alter_tenantuser_managers'),
        ('tenant_workspace', '0053_tenantbooking_booking_attachment_and_more'),
    ]

    operations = [
    ]
