# Generated by Django 5.x

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0058_tenantbooking_address_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantshipmentdocument',
            name='pod_driver_display',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='tenantshipmentdocument',
            name='pod_truck_display',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
