# Generated by Django 5.0 on 2026-05-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0066_remove_operations_denormalized_ref_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantshipmentdocument',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Draft', 'Draft'), ('Rejected', 'Rejected')], default='Pending', max_length=16),
        ),
    ]
