# Generated by Django 5.0 on 2026-05-18 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0067_alter_tenantshipmentdocument_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantshipmentdocument',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Uploaded', 'Uploaded'), ('Verified', 'Verified'), ('Draft', 'Draft'), ('Rejected', 'Rejected')], default='Pending', max_length=16),
        ),
    ]
