# Generated by Django 5.0 on 2026-05-18 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0068_alter_tenantshipmentdocument_status'),
        ('tenant_workspace', '0076_remove_tenanttruckmovementlog_movement_type'),
    ]

    operations = [
    ]
