# Generated by Django 5.0 on 2026-05-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0077_merge_20260518_1858'),
        ('tenant_workspace', '0078_tenantbooking_is_scheduled'),
    ]

    operations = [
    ]
