# Generated by Django — mobile driver login audit & JWT invalidation fields.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0079_merge_20260520_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantuser',
            name='last_login_ip',
            field=models.CharField(blank=True, default='', max_length=45),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='last_failed_login_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantuser',
            name='mobile_token_version',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Incremented on password change to invalidate outstanding mobile JWTs.',
            ),
        ),
    ]
