# Generated by Django 5.0 on 2026-05-20 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0081_tenantoperationactionlog_source_channel_ref'),
        ('tenant_workspace', '0081_tenantuser_auth_listing_index'),
    ]

    operations = [
    ]
