# Generated by Django 5.0 on 2026-05-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0086_dashboard_activity_query_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivermobilenotification',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Idempotent upsert key for operational/FCM ingest.', max_length=128),
        ),
        migrations.AlterField(
            model_name='drivermobilenotification',
            name='push_receipt_id',
            field=models.UUIDField(blank=True, help_text='Optional link to public ``PushNotificationReceipt``.', null=True),
        ),
    ]
