# Generated by Django 5.0 on 2026-05-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0087_alter_drivermobilenotification_dedupe_key_and_more'),
        ('tenant_workspace', '0090_tenantinappnotification'),
    ]

    operations = [
    ]
