# Generated by Django 5.0 on 2026-05-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0090_shipment_mobile_operational_rank'),
        ('tenant_workspace', '0091_merge_20260521_1933'),
    ]

    operations = [
    ]
