# Generated by Django 5.0 on 2026-05-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0091_merge_20260521_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesinvoicereportbooking',
            name='booking_status',
            field=models.CharField(blank=True, default='', help_text='Snapshot of booking execution status at line capture.', max_length=30),
        ),
    ]
