# Generated by Django 5.0 on 2026-05-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0093_job_detail_timeline_cursor_indexes'),
    ]

    # Do NOT remove 0093 timeline cursor indexes here — that was an accidental
    # makemigrations artifact. Index restore/ensure lives in 0095 when needed.
    operations = [
        migrations.AlterField(
            model_name='salesinvoicereportbooking',
            name='booking_status',
            field=models.CharField(blank=True, default='', help_text='Snapshot of booking execution status at line capture.', max_length=30),
        ),
        migrations.AlterField(
            model_name='tenantshipment',
            name='mobile_operational_rank',
            field=models.SmallIntegerField(db_index=True, default=10, help_text='Mobile job list priority_desc sort key (lower = higher priority).'),
        ),
    ]
