# Generated by Django 5.0 on 2026-05-27 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0092_alter_salesinvoicereportbooking_booking_status'),
        ('tenant_workspace', '0096_action_config_scope_category_indexes'),
    ]

    operations = [
    ]
