# Generated by Django 5.0 on 2026-05-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0097_merge_20260527_1230'),
        ('tenant_workspace', '0098_tenantoperationaction_mobile_metadata'),
    ]

    operations = [
    ]
