# Generated by Django 5.0 on 2026-06-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0109_tenantclientcontract_multiple_per_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantshipment',
            name='collection_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Collected', 'Collected'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
