# Generated by Django 5.0 on 2026-07-14 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant_workspace', '0115_driver_treasury_credit_debit_convention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantbooking',
            name='booking_status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Confirmed', 'Confirmed'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20),
        ),
    ]
