# Generated by Django 4.2.29 on 2026-04-06 10:11

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('superadmin', '0017_alter_activesession_redis_jti_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('tenant_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schema_registry', to='superadmin.tenantprofile')),
            ],
            options={
                'db_table': 'iroad_tenants_registry',
            },
        ),
        migrations.CreateModel(
            name='TenantSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='iroad_tenants.tenantregistry')),
            ],
            options={
                'db_table': 'iroad_tenants_domain',
            },
        ),
    ]
