# Generated by Django 5.0 on 2026-05-08 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPasswordResetOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, help_text='Driver email (from TenantUser)', max_length=254)),
                ('tenant_schema', models.CharField(db_index=True, help_text='Tenant schema name for multi-tenant isolation', max_length=100)),
                ('otp_code', models.CharField(help_text='6-digit OTP code', max_length=6)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Verified', 'Verified'), ('Used', 'Used'), ('Expired', 'Expired')], default='Pending', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0, help_text='Number of wrong verification attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='OTP expires at this time')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When OTP was verified successfully', null=True)),
                ('used_at', models.DateTimeField(blank=True, help_text='When password was reset using this OTP', null=True)),
            ],
            options={
                'verbose_name': 'Driver Password Reset OTP',
                'verbose_name_plural': 'Driver Password Reset OTPs',
                'db_table': 'mobile_api_driver_password_reset_otp',
                'ordering': ['-created_at'],
            },
        ),
    ]
