# Generated by Django 5.0 on 2026-05-27 04:27

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0002_driverpasswordresetotp_composite_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardPODReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('document_serial', models.CharField(blank=True, default='', max_length=128)),
                ('document_reference', models.CharField(blank=True, default='', max_length=128)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=200)),
                ('receiver_identity_ref', models.CharField(blank=True, default='', max_length=128)),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobile_hard_pod_receipt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HardPODVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('supervisor_id', models.CharField(blank=True, default='', max_length=64)),
                ('supervisor_label', models.CharField(blank=True, default='', max_length=200)),
                ('verified_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('verification_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobile_hard_pod_verification',
                'ordering': ['-verified_at'],
            },
        ),
        migrations.CreateModel(
            name='PODCaptureMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(blank=True, default='', max_length=32)),
                ('file_ref', models.CharField(max_length=500)),
                ('file_ref_normalized', models.CharField(db_index=True, max_length=500)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('immutable', models.BooleanField(default=False)),
                ('promoted', models.BooleanField(db_index=True, default=False)),
                ('promoted_at', models.DateTimeField(blank=True, null=True)),
                ('promoted_action_log_id', models.CharField(blank=True, default='', max_length=64)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('client_capture_id', models.CharField(blank=True, default='', max_length=128)),
            ],
            options={
                'db_table': 'mobile_pod_capture_media',
                'ordering': ['line_no', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PODCapturePromotionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_log_id', models.CharField(db_index=True, max_length=64)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('promoted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('promoted_by', models.CharField(blank=True, default='', max_length=128)),
                ('promotion_type', models.CharField(choices=[('initial', 'Initial'), ('replay', 'Replay')], default='initial', max_length=16)),
                ('execution_idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('replay_source', models.BooleanField(default=False)),
                ('bundle_integrity_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('capture_device_id', models.CharField(blank=True, default='', max_length=128)),
                ('capture_app_version', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'db_table': 'mobile_pod_capture_promotion_audit',
                'ordering': ['-promoted_at'],
            },
        ),
        migrations.CreateModel(
            name='HardPODCustodyEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('collected', 'Driver collected'), ('received', 'Physical received'), ('handoff', 'Custody handoff'), ('transferred', 'Transferred'), ('verified', 'Verified')], db_index=True, max_length=32)),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor_label', models.CharField(blank=True, default='', max_length=200)),
                ('handoff_to', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custody_events', to='mobile_api.hardpodreceipt')),
            ],
            options={
                'db_table': 'mobile_hard_pod_custody_event',
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PODCaptureBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('client_capture_id', models.CharField(max_length=128)),
                ('workflow_version', models.CharField(blank=True, default='', max_length=256)),
                ('content_hash', models.CharField(blank=True, default='', max_length=128)),
                ('bundle_status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready'), ('promoted', 'Promoted'), ('expired', 'Expired'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=16)),
                ('pod_type', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('latitude', models.CharField(blank=True, default='', max_length=32)),
                ('longitude', models.CharField(blank=True, default='', max_length=32)),
                ('media_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('promoted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('promotion_action_log_id', models.CharField(blank=True, default='', max_length=64)),
                ('replayed_from_bundle_id', models.UUIDField(blank=True, null=True)),
                ('integrity_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('capture_device_id', models.CharField(blank=True, default='', max_length=128)),
                ('capture_app_version', models.CharField(blank=True, default='', max_length=64)),
                ('rejected_reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'db_table': 'mobile_pod_capture_bundle',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_schema', 'shipment_id', 'bundle_status'], name='pod_cap_tenant_ship_status'), models.Index(fields=['tenant_schema', 'driver_id', 'created_at'], name='pod_cap_tenant_drv_created')],
            },
        ),
        migrations.AddConstraint(
            model_name='podcapturebundle',
            constraint=models.UniqueConstraint(fields=('tenant_schema', 'driver_id', 'client_capture_id'), name='pod_capture_bundle_idempotency_uq'),
        ),
        migrations.AddField(
            model_name='hardpodverification',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_pod_verifications', to='mobile_api.podcapturebundle'),
        ),
        migrations.AddField(
            model_name='hardpodreceipt',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_pod_receipts', to='mobile_api.podcapturebundle'),
        ),
        migrations.AddField(
            model_name='hardpodcustodyevent',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hard_pod_custody_events', to='mobile_api.podcapturebundle'),
        ),
        migrations.AddField(
            model_name='podcapturemedia',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_rows', to='mobile_api.podcapturebundle'),
        ),
        migrations.AddField(
            model_name='podcapturepromotionaudit',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promotion_audits', to='mobile_api.podcapturebundle'),
        ),
        migrations.AddIndex(
            model_name='podcapturemedia',
            index=models.Index(fields=['bundle', 'promoted'], name='pod_cap_media_bundle_prom'),
        ),
        migrations.AddConstraint(
            model_name='podcapturemedia',
            constraint=models.UniqueConstraint(fields=('tenant_schema', 'file_ref_normalized'), name='pod_capture_file_ref_uq'),
        ),
        migrations.AddIndex(
            model_name='podcapturepromotionaudit',
            index=models.Index(fields=['bundle', 'action_log_id'], name='pod_cap_promo_bundle_log'),
        ),
    ]
