# Generated by Django 5.0 on 2026-05-27 05:37

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0003_pod_capture_durable_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='HardPODCustodySubmissionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('collected', 'Driver collected'), ('received', 'Physical received'), ('handoff', 'Custody handoff'), ('transferred', 'Transferred'), ('verified', 'Verified')], db_index=True, max_length=32)),
                ('actor_id', models.CharField(blank=True, default='', max_length=64)),
                ('actor_label', models.CharField(blank=True, default='', max_length=200)),
                ('handoff_to', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('latitude', models.CharField(blank=True, default='', max_length=32)),
                ('longitude', models.CharField(blank=True, default='', max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobile_hard_pod_custody_submission_event',
                'ordering': ['occurred_at', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HardPODCustodySubmissionMedia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('media_type', models.CharField(blank=True, default='', max_length=32)),
                ('file_ref', models.CharField(max_length=500)),
                ('file_ref_normalized', models.CharField(db_index=True, max_length=500)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('immutable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobile_hard_pod_custody_submission_media',
                'ordering': ['line_no', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='HardPODCustodySubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('client_submission_id', models.CharField(max_length=128)),
                ('capture_bundle_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('receiver_name', models.CharField(blank=True, default='', max_length=200)),
                ('receiver_contact', models.CharField(blank=True, default='', max_length=128)),
                ('handoff_notes', models.TextField(blank=True, default='')),
                ('latitude', models.CharField(blank=True, default='', max_length=32)),
                ('longitude', models.CharField(blank=True, default='', max_length=32)),
                ('submitted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mobile_hard_pod_custody_submission',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['tenant_schema', 'shipment_id', 'submitted_at'], name='hard_pod_sub_tenant_ship')],
            },
        ),
        migrations.AddConstraint(
            model_name='hardpodcustodysubmission',
            constraint=models.UniqueConstraint(fields=('tenant_schema', 'driver_id', 'client_submission_id'), name='hard_pod_submission_idempotency_uq'),
        ),
        migrations.AddField(
            model_name='hardpodcustodysubmissionevent',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custody_events', to='mobile_api.hardpodcustodysubmission'),
        ),
        migrations.AddField(
            model_name='hardpodcustodysubmissionmedia',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_rows', to='mobile_api.hardpodcustodysubmission'),
        ),
        migrations.AddConstraint(
            model_name='hardpodcustodysubmissionmedia',
            constraint=models.UniqueConstraint(fields=('tenant_schema', 'file_ref_normalized'), name='hard_pod_sub_media_file_ref_uq'),
        ),
    ]
