# Generated by Django 5.0 on 2026-05-27 06:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0004_hard_pod_custody_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentCollectionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('action_log_id', models.CharField(blank=True, default='', max_length=64)),
                ('execution_idempotency_key', models.CharField(blank=True, default='', max_length=128)),
                ('replay_source', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('promoted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'mobile_payment_collection_audit',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCollectionEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('media_type', models.CharField(blank=True, default='', max_length=32)),
                ('file_ref', models.CharField(max_length=500)),
                ('file_ref_normalized', models.CharField(db_index=True, max_length=500)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('immutable', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'mobile_payment_collection_evidence',
                'ordering': ['line_no', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCollectionBundle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('client_payment_id', models.CharField(max_length=128)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('variance_detected', models.BooleanField(db_index=True, default=False)),
                ('payment_mode', models.CharField(blank=True, default='', max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('integrity_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('promotion_action_log_id', models.CharField(blank=True, default='', max_length=64)),
                ('replayed_from_bundle_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mobile_payment_collection_bundle',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_schema', 'driver_id', 'shipment_id'], name='mpcb_scope_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentcollectionbundle',
            constraint=models.UniqueConstraint(fields=('tenant_schema', 'driver_id', 'client_payment_id'), name='mobile_payment_bundle_idempotency_uq'),
        ),
        migrations.AddField(
            model_name='paymentcollectionaudit',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='mobile_api.paymentcollectionbundle'),
        ),
        migrations.AddField(
            model_name='paymentcollectionevidence',
            name='bundle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_rows', to='mobile_api.paymentcollectionbundle'),
        ),
        migrations.AddIndex(
            model_name='paymentcollectionaudit',
            index=models.Index(fields=['tenant_schema', 'shipment_id', 'driver_id'], name='mpca_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentcollectionevidence',
            constraint=models.UniqueConstraint(fields=('tenant_schema', 'file_ref_normalized'), name='mobile_payment_evidence_file_ref_uq'),
        ),
    ]
