# Generated by Django 5.0 on 2026-05-27 07:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0005_payment_collection_staging'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationalIssueEscalationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('from_state', models.CharField(blank=True, default='', max_length=16)),
                ('to_state', models.CharField(db_index=True, max_length=16)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('notes', models.TextField(blank=True, default='')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'mobile_operational_issue_escalation_event',
                'ordering': ['recorded_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OperationalIssueEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('media_type', models.CharField(blank=True, default='', max_length=32)),
                ('file_ref', models.CharField(max_length=500)),
                ('file_ref_normalized', models.CharField(db_index=True, max_length=500)),
                ('file_name', models.CharField(blank=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', max_length=128)),
                ('checksum', models.CharField(blank=True, default='', max_length=128)),
                ('line_no', models.PositiveIntegerField(default=1)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('immutable', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'db_table': 'mobile_operational_issue_evidence',
                'ordering': ['line_no', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalIssueTimelineEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('event_category', models.CharField(default='issue', max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('summary', models.TextField(blank=True, default='')),
                ('severity', models.CharField(blank=True, default='', max_length=16)),
                ('escalation_state', models.CharField(blank=True, default='', max_length=16)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'mobile_operational_issue_timeline_entry',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='OperationalIssue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_schema', models.CharField(db_index=True, max_length=100)),
                ('shipment_id', models.CharField(db_index=True, max_length=64)),
                ('driver_id', models.CharField(db_index=True, max_length=64)),
                ('client_issue_id', models.CharField(max_length=128)),
                ('issue_type', models.CharField(choices=[('delay', 'Delay'), ('vehicle_breakdown', 'Vehicle breakdown'), ('customer_unavailable', 'Customer unavailable'), ('payment_dispute', 'Payment dispute'), ('pod_issue', 'POD issue'), ('accident', 'Accident'), ('route_blocked', 'Route blocked'), ('other', 'Other')], db_index=True, max_length=32)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=16)),
                ('notes', models.TextField(blank=True, default='')),
                ('escalation_state', models.CharField(choices=[('open', 'Open'), ('escalated', 'Escalated'), ('acknowledged', 'Acknowledged'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], db_index=True, default='open', max_length=16)),
                ('blocking_recommended', models.BooleanField(db_index=True, default=False)),
                ('latitude', models.CharField(blank=True, default='', max_length=32)),
                ('longitude', models.CharField(blank=True, default='', max_length=32)),
                ('integrity_checksum', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'db_table': 'mobile_operational_issue',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant_schema', 'shipment_id', 'escalation_state'], name='moi_tenant_ship_state_idx'), models.Index(fields=['tenant_schema', 'driver_id', 'created_at'], name='moi_tenant_drv_created_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='operationalissue',
            constraint=models.UniqueConstraint(fields=('tenant_schema', 'driver_id', 'client_issue_id'), name='mobile_operational_issue_idempotency_uq'),
        ),
        migrations.AddField(
            model_name='operationalissueescalationevent',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalation_events', to='mobile_api.operationalissue'),
        ),
        migrations.AddField(
            model_name='operationalissueevidence',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_rows', to='mobile_api.operationalissue'),
        ),
        migrations.AddField(
            model_name='operationalissuetimelineentry',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_entries', to='mobile_api.operationalissue'),
        ),
        migrations.AddConstraint(
            model_name='operationalissueevidence',
            constraint=models.UniqueConstraint(fields=('tenant_schema', 'file_ref_normalized'), name='mobile_issue_evidence_file_ref_uq'),
        ),
    ]
