# Generated by Django 5.0 on 2026-05-27
from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mobile_api', '0006_operational_issue_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='hardpodcustodysubmission',
            name='integrity_checksum',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='hardpodcustodysubmission',
            name='promoted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='hardpodcustodysubmission',
            name='promotion_action_log_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]

