# Generated by Django 5.0 on 2026-06-01 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_api', '0008_payment_collection_variance_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hardpodreceipt',
            name='bundle',
        ),
        migrations.RemoveField(
            model_name='hardpodverification',
            name='bundle',
        ),
        migrations.CreateModel(
            name='IssueLifecycleEvent',
            fields=[
            ],
            options={
                'verbose_name': 'Issue lifecycle event',
                'verbose_name_plural': 'Issue lifecycle events',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('mobile_api.operationalissueescalationevent',),
        ),
        migrations.DeleteModel(
            name='HardPODCustodyEvent',
        ),
        migrations.DeleteModel(
            name='HardPODReceipt',
        ),
        migrations.DeleteModel(
            name='HardPODVerification',
        ),
    ]
