# Generated by Django 5.0 on 2026-02-02 07:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityNature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_nature_code', models.CharField(help_text='Unique code for entity nature', max_length=50, unique=True, verbose_name='Entity Nature Code')),
                ('entity_nature_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate'), ('government', 'Government'), ('non_profit', 'Non-Profit')], max_length=50, verbose_name='Entity Nature Type')),
                ('entity_nature_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50, verbose_name='Entity Nature Status')),
                ('entity_nature_nationality', models.CharField(choices=[('saudi', 'Saudi'), ('gcc', 'GCC'), ('foreign', 'Foreign')], max_length=50, verbose_name='Entity Nature Nationality')),
                ('entity_nature_label_arabic', models.CharField(help_text='Label in Arabic', max_length=255, verbose_name='Entity Nature Label (Arabic)')),
                ('entity_nature_residency', models.CharField(choices=[('resident', 'Resident'), ('non_resident', 'Non-Resident')], max_length=50, verbose_name='Entity Nature Residency')),
                ('entity_nature_label_english', models.CharField(help_text='Label in English', max_length=255, verbose_name='Entity Nature Label (English)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EntityAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(help_text='Unique identifier for the entity', max_length=50, unique=True, verbose_name='Entity ID')),
                ('english_name', models.CharField(help_text='Entity name in English', max_length=255, verbose_name='English Name')),
                ('display_name', models.CharField(help_text='Name to display in the system', max_length=255, verbose_name='Display Name')),
                ('entity_type', models.CharField(choices=[('llc', 'Limited Liability Company'), ('sole_proprietorship', 'Sole Proprietorship'), ('public_company', 'Public Company'), ('private_company', 'Private Company')], max_length=50, verbose_name='Entity Type')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending'), ('suspended', 'Suspended')], default='pending', max_length=50, verbose_name='Account Status')),
                ('arabic_name', models.CharField(blank=True, help_text='Entity name in Arabic (optional)', max_length=255, null=True, verbose_name='Arabic Name')),
                ('verification_status', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified'), ('pending', 'Pending Verification'), ('rejected', 'Rejected')], default='unverified', max_length=50, verbose_name='Verification Status')),
                ('primary_identifier_number', models.CharField(help_text='Commercial Registration Number', max_length=100, unique=True, verbose_name='Primary Identifier Number')),
                ('primary_identifier_issue_date', models.DateField(help_text='Date when the CR was issued', verbose_name='Primary Identifier Issue Date')),
                ('primary_identifier_expiry_date', models.DateField(help_text='Date when the CR expires', verbose_name='Primary Identifier Expiry Date')),
                ('vat_registration_status', models.CharField(choices=[('registered', 'Registered'), ('unregistered', 'Unregistered'), ('pending', 'Pending Registration'), ('exempt', 'Exempt')], max_length=50, verbose_name='VAT Registration Status')),
                ('vat_number', models.CharField(blank=True, help_text='15-digit VAT registration number', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='VAT Number must be 15 digits', regex='^\\d{15}$')], verbose_name='VAT Number')),
                ('vat_registration_date', models.DateField(blank=True, help_text='Date when VAT was registered', null=True, verbose_name='VAT Registration Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_nature', models.ForeignKey(help_text='Select the entity nature', on_delete=django.db.models.deletion.PROTECT, related_name='entity_accounts', to='core.entitynature', verbose_name='Entity Nature')),
            ],
        ),
    ]
