# Generated by Django 5.0 on 2026-02-02 09:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaccount',
            name='arabic_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Arabic Name'),
        ),
        migrations.AlterField(
            model_name='entityaccount',
            name='display_name',
            field=models.CharField(max_length=255, verbose_name='Display Name'),
        ),
        migrations.AlterField(
            model_name='entityaccount',
            name='english_name',
            field=models.CharField(max_length=255, verbose_name='English Name'),
        ),
        migrations.AlterField(
            model_name='entityaccount',
            name='entity_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Entity ID'),
        ),
        migrations.AlterField(
            model_name='entityaccount',
            name='entity_nature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entity_accounts', to='core.entitynature', verbose_name='Entity Nature'),
        ),
        migrations.AlterField(
            model_name='entityaccount',
            name='primary_identifier_expiry_date',
            field=models.DateField(verbose_name='Primary Identifier Expiry Date'),
        ),
        migrations.AlterField(
            model_name='entityaccount',
            name='primary_identifier_issue_date',
            field=models.DateField(verbose_name='Primary Identifier Issue Date'),
        ),
        migrations.AlterField(
            model_name='entityaccount',
            name='primary_identifier_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Primary Identifier Number'),
        ),
        migrations.AlterField(
            model_name='entityaccount',
            name='vat_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='VAT Number must be 15 digits', regex='^\\d{15}$')], verbose_name='VAT Number'),
        ),
        migrations.AlterField(
            model_name='entityaccount',
            name='vat_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='VAT Registration Date'),
        ),
    ]
