# Generated by Django 5.0 on 2026-02-02 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_entityaccount_arabic_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='entitynature',
            name='entity_nature_code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Entity Nature Code'),
        ),
        migrations.AlterField(
            model_name='entitynature',
            name='entity_nature_label_arabic',
            field=models.CharField(max_length=255, verbose_name='Entity Nature Label (Arabic)'),
        ),
        migrations.AlterField(
            model_name='entitynature',
            name='entity_nature_label_english',
            field=models.CharField(max_length=255, verbose_name='Entity Nature Label (English)'),
        ),
        migrations.CreateModel(
            name='DocumentMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.CharField(max_length=50, unique=True)),
                ('document_title', models.CharField(max_length=255)),
                ('document_number', models.CharField(blank=True, max_length=100, null=True)),
                ('document_certificate_ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField()),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('is_expiry_applicable', models.BooleanField(default=False)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('validity_status', models.CharField(choices=[('valid', 'Valid'), ('expired', 'Expired'), ('under_review', 'Under Review')], default='valid', max_length=20)),
                ('document_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('pending', 'Pending')], default='active', max_length=20)),
                ('attachment_file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.entityaccount')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='core.documenttype')),
            ],
        ),
    ]
