# Generated by Django 5.0 on 2026-02-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_subaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmaster',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
