# Generated by Django 5.0 on 2026-02-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_entityaccountcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaccount',
            name='entity_id',
            field=models.CharField(max_length=50, verbose_name='Entity ID'),
        ),
    ]
