# Generated by Django 5.0 on 2026-02-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_entityaccount_entity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityaccount',
            name='primary_identifier_number',
            field=models.CharField(max_length=100, verbose_name='Primary Identifier Number'),
        ),
    ]
