from django.urls import path

from .views import (
    TenantAutoNumberConfigurationView,
    TenantClientAccountCreateView,
    TenantClientAccountDeleteView,
    TenantClientAccountEditView,
    TenantClientSalesReportView,
    TenantClientAccountSettingsView,
    TenantClientAccountToggleStatusView,
    TenantClientAccountView,
    TenantClientAttachmentsListView,
    TenantClientAttachmentsView,
    TenantClientContactsListView,
    TenantClientContactsView,
    TenantClientContractListView,
    TenantClientContractSettingsView,
    TenantClientContractView,
    TenantClientDetailsView,
    TenantCriticalAccountChangesView,
    TenantSubscriptionBillingView,
    TenantSubscriptionPlanView,
    TenantDashboardView,
    TenantUsersAdministrationDeleteView,
    TenantUsersAdministrationEditView,
    TenantUsersAdministrationExportView,
    TenantRolesPermissionsCreateView,
    TenantRolesPermissionsDeleteView,
    TenantRolesPermissionsEditView,
    TenantRolesPermissionsExportView,
    TenantRolesPermissionsToggleStatusView,
    TenantRolesPermissionsView,
    TenantRolePermissionChangesView,
    TenantLoginSessionEventsView,
    TenantInvoiceDownloadView,
    TenantInvoiceExportAllView,
    TenantLogoutView,
    TenantMyAccountView,
    TenantOrganizationProfileEditView,
    TenantOrganizationProfileView,
    TenantUsersAdministrationCreateView,
    TenantUsersAdministrationToggleStatusView,
    TenantUsersAdministrationView,
)

app_name = 'iroad_tenants'


urlpatterns = [
    path('dashboard/', TenantDashboardView.as_view(), name='tenant_dashboard'),
    path(
        'administration/organization-profile/',
        TenantOrganizationProfileView.as_view(),
        name='tenant_organization_profile',
    ),
    path(
        'administration/organization-profile/edit/',
        TenantOrganizationProfileEditView.as_view(),
        name='tenant_organization_profile_edit',
    ),
    path(
        'configuration/auto-number/',
        TenantAutoNumberConfigurationView.as_view(),
        name='tenant_auto_number_configuration',
    ),
    path(
        'administration/users/',
        TenantUsersAdministrationView.as_view(),
        name='tenant_users_administration',
    ),
    path(
        'administration/users/create/',
        TenantUsersAdministrationCreateView.as_view(),
        name='tenant_users_administration_create',
    ),
    path(
        'administration/users/<uuid:user_id>/edit/',
        TenantUsersAdministrationEditView.as_view(),
        name='tenant_users_administration_edit',
    ),
    path(
        'administration/users/<uuid:user_id>/toggle-status/',
        TenantUsersAdministrationToggleStatusView.as_view(),
        name='tenant_users_administration_toggle_status',
    ),
    path(
        'administration/users/<uuid:user_id>/delete/',
        TenantUsersAdministrationDeleteView.as_view(),
        name='tenant_users_administration_delete',
    ),
    path(
        'administration/users/export/',
        TenantUsersAdministrationExportView.as_view(),
        name='tenant_users_administration_export',
    ),
    path(
        'administration/roles/',
        TenantRolesPermissionsView.as_view(),
        name='tenant_roles_permissions',
    ),
    path(
        'administration/roles/create/',
        TenantRolesPermissionsCreateView.as_view(),
        name='tenant_roles_permissions_create',
    ),
    path(
        'administration/roles/<uuid:role_id>/edit/',
        TenantRolesPermissionsEditView.as_view(),
        name='tenant_roles_permissions_edit',
    ),
    path(
        'administration/roles/<uuid:role_id>/toggle-status/',
        TenantRolesPermissionsToggleStatusView.as_view(),
        name='tenant_roles_permissions_toggle_status',
    ),
    path(
        'administration/roles/<uuid:role_id>/delete/',
        TenantRolesPermissionsDeleteView.as_view(),
        name='tenant_roles_permissions_delete',
    ),
    path(
        'administration/roles/export/',
        TenantRolesPermissionsExportView.as_view(),
        name='tenant_roles_permissions_export',
    ),
    path(
        'administration/subscription-plan/',
        TenantSubscriptionPlanView.as_view(),
        name='tenant_subscription_plan',
    ),
    path(
        'administration/subscription-billing/',
        TenantSubscriptionBillingView.as_view(),
        name='tenant_subscription_billing',
    ),
    path(
        'administration/subscription-billing/export-all/',
        TenantInvoiceExportAllView.as_view(),
        name='tenant_invoice_export_all',
    ),
    path(
        'administration/subscription-billing/invoice/<uuid:invoice_id>/download/',
        TenantInvoiceDownloadView.as_view(),
        name='tenant_invoice_download',
    ),
    path(
        'administration/audit/login-session-events/',
        TenantLoginSessionEventsView.as_view(),
        name='tenant_login_session_events',
    ),
    path(
        'administration/audit/role-permission-changes/',
        TenantRolePermissionChangesView.as_view(),
        name='tenant_role_permission_changes',
    ),
    path(
        'administration/audit/critical-account-changes/',
        TenantCriticalAccountChangesView.as_view(),
        name='tenant_critical_account_changes',
    ),
    path(
        'crm/clients/account/',
        TenantClientAccountView.as_view(),
        name='tenant_client_account',
    ),
    path(
        'crm/clients/account/create/',
        TenantClientAccountCreateView.as_view(),
        name='tenant_client_account_create',
    ),
    path(
        'crm/clients/account/<str:account_no>/edit/',
        TenantClientAccountEditView.as_view(),
        name='tenant_client_account_edit',
    ),
    path(
        'crm/clients/account/<str:account_no>/toggle-status/',
        TenantClientAccountToggleStatusView.as_view(),
        name='tenant_client_account_toggle_status',
    ),
    path(
        'crm/clients/account/<str:account_no>/delete/',
        TenantClientAccountDeleteView.as_view(),
        name='tenant_client_account_delete',
    ),
    path(
        'crm/clients/account/<str:account_no>/sales-report/',
        TenantClientSalesReportView.as_view(),
        name='tenant_client_sales_report',
    ),
    path(
        'crm/clients/account/settings/',
        TenantClientAccountSettingsView.as_view(),
        name='tenant_client_account_settings',
    ),
    path(
        'crm/clients/attachments/',
        TenantClientAttachmentsView.as_view(),
        name='tenant_client_attachments',
    ),
    path(
        'crm/clients/attachments/create/',
        TenantClientAttachmentsView.as_view(),
        name='tenant_client_attachments_create',
    ),
    path(
        'crm/clients/attachments/list/',
        TenantClientAttachmentsListView.as_view(),
        name='tenant_client_attachments_list',
    ),
    path(
        'crm/clients/contacts/',
        TenantClientContactsView.as_view(),
        name='tenant_client_contacts',
    ),
    path(
        'crm/clients/contacts/list/',
        TenantClientContactsListView.as_view(),
        name='tenant_client_contacts_list',
    ),
    path(
        'crm/clients/contracts/',
        TenantClientContractView.as_view(),
        name='tenant_client_contract',
    ),
    path(
        'crm/clients/contracts/list/',
        TenantClientContractListView.as_view(),
        name='tenant_client_contract_list',
    ),
    path(
        'crm/clients/contracts/settings/',
        TenantClientContractSettingsView.as_view(),
        name='tenant_client_contract_settings',
    ),
    path(
        'crm/clients/details/',
        TenantClientDetailsView.as_view(),
        name='tenant_client_details',
    ),
    path('my-account/', TenantMyAccountView.as_view(), name='tenant_my_account'),
    path('logout/', TenantLogoutView.as_view(), name='tenant_logout'),
]
