# Generated by Django 4.2.29 on 2026-03-26 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_adminuser_created_by_adminuser_updated_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_type', models.CharField(choices=[('Login', 'Login'), ('Logout', 'Logout'), ('Token_Refresh', 'Token_Refresh')], max_length=20)),
                ('status', models.CharField(choices=[('Success', 'Success'), ('Failed', 'Failed'), ('Blocked', 'Blocked')], max_length=20)),
                ('user_domain', models.CharField(default='Admin', max_length=50)),
                ('email_used', models.EmailField(max_length=254)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'superadmin_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('failed_count', models.IntegerField(default=0)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempt_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'superadmin_login_attempts',
            },
        ),
        migrations.CreateModel(
            name='AdminSecuritySettings',
            fields=[
                ('setting_id', models.CharField(default='ADMIN-SEC-CONF', max_length=50, primary_key=True, serialize=False)),
                ('session_timeout_minutes', models.IntegerField(default=240)),
                ('max_failed_logins', models.IntegerField(default=3)),
                ('lockout_duration_minutes', models.IntegerField(default=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Security Settings',
                'db_table': 'superadmin_security_settings',
            },
        ),
        migrations.CreateModel(
            name='AdminAuthToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('token_type', models.CharField(choices=[('invite', 'invite'), ('password_reset', 'password_reset')], max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'superadmin_auth_tokens',
            },
        ),
    ]
