# Generated by Django 4.2.29 on 2026-03-26 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0004_accesslog_loginattempt_adminsecuritysettings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currency_code', models.CharField(help_text='ISO Currency Code e.g. SAR, USD', max_length=10, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('currency_symbol', models.CharField(max_length=10)),
                ('decimal_places', models.IntegerField(blank=True, default=2, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currencies_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'master_currencies',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_code', models.CharField(help_text='ISO Country Code e.g. SA, US, AE', max_length=10, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'master_countries',
                'ordering': ['name_en'],
            },
        ),
    ]
