# Generated by Django 4.2.29 on 2026-03-26 09:00

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0005_currency_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxCode',
            fields=[
                ('tax_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100)),
                ('name_ar', models.CharField(max_length=100)),
                ('rate_percent', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_default_for_country', models.BooleanField(default=False)),
                ('is_international_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicable_country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_codes', to='superadmin.country')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_codes_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_codes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_tax_codes',
                'ordering': ['tax_code'],
            },
        ),
        migrations.CreateModel(
            name='LegalIdentity',
            fields=[
                ('identity_id', models.CharField(default='GLOBAL-LEGAL-IDENTITY', max_length=50, primary_key=True, serialize=False)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='legal/')),
                ('company_name_en', models.CharField(max_length=100)),
                ('company_name_ar', models.CharField(max_length=100)),
                ('commercial_register', models.CharField(max_length=50)),
                ('tax_number', models.CharField(max_length=50)),
                ('registered_address', models.TextField()),
                ('support_email', models.EmailField(max_length=100)),
                ('support_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_country_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='superadmin.country')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_legal_identity',
            },
        ),
        migrations.CreateModel(
            name='GlobalSystemRules',
            fields=[
                ('rule_id', models.CharField(default='GLOBAL-SYSTEM-RULES', max_length=50, primary_key=True, serialize=False)),
                ('system_timezone', models.CharField(default='Asia/Riyadh', max_length=100)),
                ('default_date_format', models.CharField(choices=[('YYYY-MM-DD', 'YYYY-MM-DD'), ('DD/MM/YYYY', 'DD/MM/YYYY')], default='DD/MM/YYYY', max_length=20)),
                ('grace_period_days', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('standard_billing_cycle', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_system_rules',
            },
        ),
        migrations.CreateModel(
            name='GeneralTaxSettings',
            fields=[
                ('setting_id', models.CharField(default='GLOBAL-TAX-SETTING', max_length=50, primary_key=True, serialize=False)),
                ('prices_include_tax', models.BooleanField(default=False)),
                ('location_verification', models.CharField(choices=[('Profile_Only', 'Profile Only'), ('Audit_Only', 'Audit Only'), ('Enforce_Profile_Match', 'Enforce Profile Match')], default='Profile_Only', max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_general_tax_settings',
            },
        ),
        migrations.CreateModel(
            name='FXRateChangeLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('old_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('new_rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fx_change_logs', to='superadmin.currency')),
            ],
            options={
                'db_table': 'config_fx_change_log',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('fx_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.000001'))])),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates', to='superadmin.currency')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_exchange_rates',
            },
        ),
        migrations.CreateModel(
            name='BaseCurrencyConfig',
            fields=[
                ('setting_id', models.CharField(default='GLOBAL-BASE-CURRENCY', max_length=50, primary_key=True, serialize=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='base_currency_config', to='superadmin.currency')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'config_base_currency',
            },
        ),
    ]
