# Generated by Django 5.0 on 2026-03-26 10:33

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_taxcode_legalidentity_globalsystemrules_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOnsPricingPolicy',
            fields=[
                ('policy_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('policy_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('extra_internal_user_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_internal_truck_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_external_truck_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_driver_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_shipment_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('extra_storage_gb_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_addons_policy',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('plan_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('plan_name_en', models.CharField(max_length=50, unique=True)),
                ('plan_name_ar', models.CharField(max_length=50, unique=True)),
                ('base_cycle_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('max_internal_users', models.IntegerField(default=-1, help_text='-1 means Unlimited')),
                ('max_internal_trucks', models.IntegerField(default=-1)),
                ('max_external_trucks', models.IntegerField(default=-1)),
                ('max_active_drivers', models.IntegerField(default=-1)),
                ('max_monthly_shipments', models.IntegerField(default=-1)),
                ('max_storage_gb', models.IntegerField(default=-1)),
                ('has_driver_app', models.BooleanField(default=False)),
                ('backup_restore_level', models.CharField(choices=[('Standard', 'Standard'), ('Extended', 'Extended'), ('Premium', 'Premium')], default='Standard', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plans_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscription_plans',
                'ordering': ['plan_name_en'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('promo_code_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('Percentage', 'Percentage'), ('Fixed_Amount', 'Fixed Amount')], default='Percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_duration', models.CharField(choices=[('Apply_Once', 'Apply Once'), ('Recurring', 'Recurring')], default='Apply_Once', max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('current_uses', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('applicable_plans', models.ManyToManyField(blank=True, related_name='promo_codes', to='superadmin.subscriptionplan')),
            ],
            options={
                'db_table': 'subscription_promo_codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlanPricingCycle',
            fields=[
                ('pricing_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_of_cycles', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_pricing', to='superadmin.currency')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_cycles', to='superadmin.subscriptionplan')),
            ],
            options={
                'db_table': 'subscription_plan_pricing',
                'ordering': ['number_of_cycles'],
                'unique_together': {('plan', 'number_of_cycles', 'currency')},
            },
        ),
    ]
