# Generated by Django 5.0 on 2026-03-26 11:25

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_addonspricingpolicy_subscriptionplan_promocode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('iban_number', models.CharField(help_text='IBAN format: e.g. SA0380000000608010167519', max_length=34)),
                ('account_number', models.CharField(max_length=30)),
                ('swift_code', models.CharField(blank=True, max_length=11, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='superadmin.currency')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_accounts_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_bank_accounts',
                'ordering': ['bank_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('gateway_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gateway_name', models.CharField(max_length=50)),
                ('environment', models.CharField(choices=[('Test', 'Test'), ('Live', 'Live')], default='Test', max_length=10)),
                ('credentials_payload', models.JSONField(help_text='JSON object with gateway credentials')),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateways_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gateways_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_gateways',
                'ordering': ['gateway_name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('method_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('method_name_en', models.CharField(max_length=100)),
                ('method_name_ar', models.CharField(max_length=100)),
                ('method_type', models.CharField(choices=[('Online_Gateway', 'Online Gateway'), ('Offline_Bank', 'Offline Bank Transfer')], max_length=20)),
                ('supported_currencies', models.JSONField(default=list, help_text='Array of currency codes e.g. ["SAR","USD"]')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='payment_methods/')),
                ('display_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods_created', to=settings.AUTH_USER_MODEL)),
                ('dedicated_bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='superadmin.bankaccount')),
                ('gateway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods', to='superadmin.paymentgateway')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_methods_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_methods',
                'ordering': ['display_order'],
            },
        ),
    ]
