# Generated by Django 5.0 on 2026-03-26 11:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0008_bankaccount_paymentgateway_paymentmethod'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('recipient', models.CharField(help_text='Email, phone number, or FCM token', max_length=255)),
                ('client_id', models.CharField(blank=True, help_text='Tenant reference for filtering', max_length=100, null=True)),
                ('channel_type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS'), ('Push', 'Push Notification')], max_length=10)),
                ('trigger_source', models.CharField(help_text='e.g. Event: OTP_Requested', max_length=255)),
                ('delivery_status', models.CharField(choices=[('Sent', 'Sent'), ('Failed', 'Failed'), ('Bounced', 'Bounced')], max_length=20)),
                ('error_details', models.TextField(blank=True, null=True)),
                ('dispatched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comm_logs',
                'ordering': ['-dispatched_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemBanner',
            fields=[
                ('banner_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('message_en', models.TextField()),
                ('message_ar', models.TextField()),
                ('severity', models.CharField(choices=[('Info', 'Info (Blue)'), ('Warning', 'Warning (Yellow)'), ('Critical', 'Critical (Red)')], default='Info', max_length=20)),
                ('is_dismissible', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'comm_system_banners',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.CreateModel(
            name='CommGateway',
            fields=[
                ('gateway_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('gateway_type', models.CharField(choices=[('Email', 'Email (SMTP)'), ('SMS', 'SMS API')], max_length=10)),
                ('provider_name', models.CharField(max_length=100)),
                ('host_url', models.CharField(max_length=255)),
                ('port', models.IntegerField(blank=True, null=True)),
                ('username_key', models.CharField(max_length=255)),
                ('password_secret', models.CharField(help_text='Stored securely. Never displayed after save.', max_length=255)),
                ('sender_id', models.CharField(help_text='From email address or SMS sender name', max_length=100)),
                ('encryption_type', models.CharField(blank=True, choices=[('TLS', 'TLS'), ('SSL', 'SSL'), ('None', 'None')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comm_gateways',
                'ordering': ['gateway_type'],
            },
        ),
        migrations.CreateModel(
            name='InternalAlertRoute',
            fields=[
                ('route_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('trigger_event', models.CharField(choices=[('New_Tenant_Registered', 'New Tenant Registered'), ('High_Priority_Ticket', 'High Priority Ticket'), ('Payment_Failed', 'Payment Failed'), ('Subscription_Expired', 'Subscription Expired'), ('Bank_Transfer_Pending', 'Bank Transfer Pending'), ('System_Error', 'System Error')], max_length=50)),
                ('notify_custom_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notify_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_routes', to='superadmin.role')),
            ],
            options={
                'db_table': 'comm_alert_routes',
                'ordering': ['trigger_event'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('template_name', models.CharField(max_length=100, unique=True)),
                ('channel_type', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('category', models.CharField(choices=[('Transactional', 'Transactional'), ('Promotional', 'Promotional')], max_length=20)),
                ('subject_en', models.CharField(blank=True, max_length=255, null=True)),
                ('subject_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comm_templates',
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='EventMapping',
            fields=[
                ('mapping_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('system_event', models.CharField(choices=[('OTP_Requested', 'OTP Requested'), ('Password_Changed', 'Password Changed'), ('Invoice_Paid', 'Invoice Paid'), ('Subscription_Activated', 'Subscription Activated'), ('Subscription_Expired', 'Subscription Expired'), ('Subscription_Renewed', 'Subscription Renewed'), ('Account_Suspended', 'Account Suspended'), ('Welcome_Email', 'Welcome Email'), ('Password_Reset_Requested', 'Password Reset Requested'), ('Payment_Failed', 'Payment Failed'), ('Support_Ticket_Created', 'Support Ticket Created'), ('Support_Ticket_Replied', 'Support Ticket Replied')], max_length=50, unique=True)),
                ('primary_channel', models.CharField(choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=10)),
                ('fallback_channel', models.CharField(blank=True, choices=[('Email', 'Email'), ('SMS', 'SMS')], max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fallback_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_mappings', to='superadmin.notificationtemplate')),
                ('primary_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_mappings', to='superadmin.notificationtemplate')),
            ],
            options={
                'db_table': 'comm_event_mappings',
                'ordering': ['system_event'],
            },
        ),
        migrations.CreateModel(
            name='PushNotification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('internal_name', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('message_en', models.TextField()),
                ('message_ar', models.TextField()),
                ('action_link', models.URLField(blank=True, null=True)),
                ('trigger_mode', models.CharField(choices=[('Manual_Broadcast', 'Manual Broadcast'), ('System_Event', 'System Event')], max_length=20)),
                ('linked_event', models.CharField(blank=True, choices=[('OTP_Requested', 'OTP Requested'), ('Password_Changed', 'Password Changed'), ('Invoice_Paid', 'Invoice Paid'), ('Subscription_Activated', 'Subscription Activated'), ('Subscription_Expired', 'Subscription Expired'), ('Subscription_Renewed', 'Subscription Renewed'), ('Account_Suspended', 'Account Suspended'), ('Welcome_Email', 'Welcome Email'), ('Password_Reset_Requested', 'Password Reset Requested'), ('Payment_Failed', 'Payment Failed'), ('Support_Ticket_Created', 'Support Ticket Created'), ('Support_Ticket_Replied', 'Support Ticket Replied')], max_length=50, null=True)),
                ('target_audience', models.CharField(blank=True, choices=[('All', 'All Users'), ('Tenants', 'Tenants Only'), ('Drivers', 'Drivers Only'), ('Specific', 'Specific Target')], max_length=20, null=True)),
                ('specific_target_id', models.CharField(blank=True, max_length=100, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('dispatch_status', models.CharField(choices=[('Draft', 'Draft'), ('Scheduled', 'Scheduled'), ('Completed', 'Completed')], default='Draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comm_push_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
