# Generated by Django 4.2.29 on 2026-03-27 04:51

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_commlog_systembanner_commgateway_internalalertroute_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('order_classification', models.CharField(choices=[('New_Subscription', 'New Subscription'), ('Renewal', 'Renewal'), ('Upgrade', 'Upgrade'), ('Downgrade', 'Downgrade'), ('Add_ons', 'Add-ons')], default='New_Subscription', max_length=20)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('exchange_rate_snapshot', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10)),
                ('base_currency_equivalent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order_status', models.CharField(choices=[('Draft', 'Draft'), ('Pending_Payment', 'Pending Payment'), ('Paid', 'Paid'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('projected_expiry_date', models.DateField(blank=True, null=True)),
                ('projected_max_users', models.IntegerField(blank=True, null=True)),
                ('projected_max_internal_trucks', models.IntegerField(blank=True, null=True)),
                ('projected_max_external_trucks', models.IntegerField(blank=True, null=True)),
                ('projected_max_drivers', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_created', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_orders', to='superadmin.currency')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.paymentmethod')),
                ('projected_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projected_orders', to='superadmin.subscriptionplan')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='superadmin.promocode')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.taxcode')),
            ],
            options={
                'db_table': 'crm_subscription_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantProfile',
            fields=[
                ('tenant_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50)),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('primary_email', models.EmailField(max_length=100)),
                ('primary_phone', models.CharField(max_length=20)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Suspended_Billing', 'Suspended - Billing'), ('Suspended_Violation', 'Suspended - Violation'), ('Churned', 'Churned')], default='Active', max_length=30)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('total_ltv', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subscription_start_date', models.DateField(blank=True, null=True)),
                ('subscription_expiry_date', models.DateField(blank=True, null=True)),
                ('active_max_users', models.IntegerField(default=0)),
                ('active_max_internal_trucks', models.IntegerField(default=0)),
                ('active_max_external_trucks', models.IntegerField(default=0)),
                ('active_max_drivers', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_sales_rep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tenants', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tenant_profiles', to='superadmin.country')),
                ('current_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_tenants', to='superadmin.subscriptionplan')),
            ],
            options={
                'db_table': 'crm_tenant_profiles',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('Order_Payment', 'Order Payment'), ('Wallet_TopUp', 'Wallet Top-Up'), ('Refund', 'Refund')], default='Order_Payment', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('exchange_rate_snapshot', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10)),
                ('base_currency_equivalent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('gateway_ref', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='receipts/')),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crm_transactions', to='superadmin.currency')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='superadmin.subscriptionorder')),
                ('payment_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.paymentmethod')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_transactions', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='superadmin.tenantprofile')),
            ],
            options={
                'db_table': 'crm_transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='superadmin.tenantprofile'),
        ),
        migrations.CreateModel(
            name='StandardInvoice',
            fields=[
                ('invoice_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Issued', 'Issued'), ('Paid', 'Paid'), ('Void', 'Void')], default='Issued', max_length=10)),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_tax_number', models.CharField(max_length=50)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_address', models.TextField(blank=True, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('grand_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('exchange_rate_snapshot', models.DecimalField(decimal_places=6, default=Decimal('1.000000'), max_digits=10)),
                ('base_currency_equivalent_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='standard_invoices', to='superadmin.currency')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='superadmin.subscriptionorder')),
                ('tax_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='superadmin.taxcode')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='superadmin.tenantprofile')),
            ],
            options={
                'db_table': 'crm_invoices',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='OrderPlanLine',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_of_cycles', models.IntegerField(default=1)),
                ('plan_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pro_rata_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_lines', to='superadmin.subscriptionorder')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='superadmin.subscriptionplan')),
            ],
            options={
                'db_table': 'crm_order_plan_lines',
            },
        ),
        migrations.CreateModel(
            name='OrderAddonLine',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('Add', 'Add'), ('Reduce', 'Reduce')], default='Add', max_length=10)),
                ('add_on_type', models.CharField(choices=[('Extra_User', 'Extra Internal User'), ('Extra_Internal_Truck', 'Extra Internal Truck'), ('Extra_External_Truck', 'Extra External Truck'), ('Extra_Driver', 'Extra Driver'), ('Extra_Shipment', 'Extra Shipment'), ('Extra_Storage_GB', 'Extra Storage (GB)')], max_length=30)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_cycles', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('pro_rata_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addon_lines', to='superadmin.subscriptionorder')),
            ],
            options={
                'db_table': 'crm_order_addon_lines',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('line_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='line_items', to='superadmin.standardinvoice')),
            ],
            options={
                'db_table': 'crm_invoice_line_items',
            },
        ),
        migrations.CreateModel(
            name='CRMNote',
            fields=[
                ('note_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('General', 'General'), ('Sales_Call', 'Sales Call'), ('Billing_Issue', 'Billing Issue'), ('Complaint', 'Complaint')], default='General', max_length=20)),
                ('note_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_notes', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crm_notes', to='superadmin.tenantprofile')),
            ],
            options={
                'db_table': 'crm_notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
