# Generated by Django 4.2.29 on 2026-03-27 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0010_subscriptionorder_tenantprofile_transaction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=100, unique=True)),
                ('name_ar', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_categories_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_categories',
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('ticket_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('ticket_no', models.CharField(help_text='Auto-generated e.g. TKT-10001', max_length=20, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('New', 'New'), ('In_Progress', 'In Progress'), ('Pending_Client', 'Pending Client'), ('Closed', 'Closed')], default='New', max_length=20)),
                ('created_by', models.CharField(help_text='Tenant User ID who opened the ticket', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='superadmin.supportcategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_tickets', to='superadmin.tenantprofile')),
            ],
            options={
                'db_table': 'support_tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('reply_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('Tenant_User', 'Tenant User'), ('Admin_Support', 'Admin Support'), ('System_Bot', 'System Bot')], max_length=20)),
                ('sender_id', models.CharField(help_text='ID of person or bot who sent this', max_length=100)),
                ('message_body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_attachments/')),
                ('is_internal', models.BooleanField(default=False, help_text='If True, hidden from Tenant completely')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='superadmin.supportticket')),
            ],
            options={
                'db_table': 'support_ticket_replies',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CannedResponse',
            fields=[
                ('template_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('message_body', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canned_responses_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_canned_responses',
                'ordering': ['title'],
            },
        ),
    ]
