# Generated by Django 4.2.29 on 2026-03-27 06:38

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0011_supportcategory_supportticket_ticketreply_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantSecuritySettings',
            fields=[
                ('setting_id', models.CharField(default='TENANT-SEC-CONF', max_length=50, primary_key=True, serialize=False)),
                ('tenant_web_timeout_hours', models.IntegerField(default=12, validators=[django.core.validators.MinValueValidator(1)])),
                ('driver_app_timeout_days', models.IntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_failed_logins', models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1)])),
                ('lockout_duration_minutes', models.IntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_tenant_settings',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('audit_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('Create', 'Create'), ('Update', 'Update'), ('Delete', 'Delete'), ('Status_Change', 'Status Change')], max_length=20)),
                ('module_name', models.CharField(help_text='e.g. Tax Settings, Subscription Plans', max_length=100)),
                ('record_id', models.CharField(help_text='ID of the modified entity', max_length=100)),
                ('old_payload', models.JSONField(blank=True, help_text='State before update. Null on Create.', null=True)),
                ('new_payload', models.JSONField(blank=True, help_text='State after update. Null on Delete.', null=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ActiveSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('user_domain', models.CharField(choices=[('Admin', 'Admin'), ('Tenant_User', 'Tenant User'), ('Driver', 'Driver')], max_length=20)),
                ('reference_id', models.CharField(help_text='User or Driver ID', max_length=100)),
                ('reference_name', models.CharField(blank=True, help_text='Display name for UI', max_length=200, null=True)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'security_active_sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
