# Generated by Django 4.2.29 on 2026-04-06 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0012_tenantsecuritysettings_auditlog_activesession'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='scheduled_downgrade_effective_date',
            field=models.DateField(blank=True, help_text='Date the subscriber moves to the lower plan (end of current cycle).', null=True),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='scheduled_downgrade_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants_pending_downgrade', to='superadmin.subscriptionplan'),
        ),
    ]
