# Generated by Django 4.2.29 on 2026-04-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0016_workspace_schema_order_snapshots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='redis_jti',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Redis JTI for CP Kill Switch / mass revoke.', max_length=128),
        ),
        migrations.AlterField(
            model_name='tenantprofile',
            name='api_bridge_secret_hash',
            field=models.TextField(blank=True, default='', help_text='Hashed secret for tenant API bridge (/api/v1/). Rotated from Control Panel.'),
        ),
    ]
