# Generated by Django 4.2.29 on 2026-04-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0017_alter_activesession_redis_jti_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='portal_bootstrap_password_hash',
            field=models.TextField(blank=True, default='', help_text='Hashed initial tenant-portal password set at provisioning (CP-PCS-P1 handover). Plaintext sent once in welcome email; not shown in CP.'),
        ),
    ]
