# Generated by Django 5.0.10 on 2026-04-20 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0021_push_receipts_and_token_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Initial request detail'),
        ),
    ]
