# Generated by Django 5.0 on 2026-04-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0023_soft_delete_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='tenantprofile',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
