# Generated by Django 5.0 on 2026-04-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0024_tenantprofile_first_name_tenantprofile_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardinvoice',
            name='supplier_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='standardinvoice',
            name='supplier_commercial_register',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='standardinvoice',
            name='supplier_name_ar',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standardinvoice',
            name='supplier_support_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='standardinvoice',
            name='supplier_support_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
