# Generated by Django 6.0.3 on 2026-04-25 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0024_tenantprofile_first_name_tenantprofile_last_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalAlertNotification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('trigger_event', models.CharField(choices=[('New_Tenant_Registered', 'New Tenant Registered'), ('High_Priority_Ticket', 'High Priority Ticket'), ('Payment_Failed', 'Payment Failed'), ('Subscription_Expired', 'Subscription Expired'), ('Bank_Transfer_Pending', 'Bank Transfer Pending'), ('System_Error', 'System Error')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('context_payload', models.JSONField(blank=True, default=dict)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_alert_notifications', to='superadmin.adminuser')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='superadmin.internalalertroute')),
            ],
            options={
                'db_table': 'comm_internal_alert_notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
