# Generated by Django 5.0 on 2026-04-24 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0025_standardinvoice_supplier_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsecuritysettings',
            name='otp_timeout_seconds',
            field=models.IntegerField(default=240),
        ),
    ]
