# Generated by Django 5.0 on 2026-04-27 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0025_internalalertnotification'),
        ('superadmin', '0026_adminsecuritysettings_otp_timeout_seconds'),
    ]

    operations = [
    ]
