# Generated by Django 5.0 on 2026-04-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0027_merge_20260427_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantprofile',
            name='registered_address',
            field=models.TextField(blank=True, default='', help_text='Registered address for tenant profile.'),
        ),
    ]
