# Generated by Django 5.0 on 2026-04-27 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0028_tenantprofile_registered_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsecuritysettings',
            name='session_timeout_minutes',
            field=models.IntegerField(default=1440),
        ),
    ]
