# Generated by Django — refresh TENANT_WELCOME_EMAIL to drop legacy secret blocks
# (initial password, tenant UUID, API bridge key) from DB-stored HTML.

from django.db import migrations


def refresh_tenant_welcome_bodies(apps, schema_editor):
    from superadmin.communication_helpers import (
        refresh_tenant_welcome_email_template_from_defaults,
    )

    refresh_tenant_welcome_email_template_from_defaults()


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0033_planpricingcycle_is_admin_only_cycle'),
    ]

    operations = [
        migrations.RunPython(refresh_tenant_welcome_bodies, noop_reverse),
    ]
