# Generated by Django 5.0 on 2026-05-06 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0034_refresh_tenant_welcome_email_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventmapping',
            name='system_event',
            field=models.CharField(choices=[('OTP_Requested', 'OTP Requested'), ('Password_Changed', 'Password Changed'), ('Invoice_Paid', 'Invoice Paid'), ('Subscription_Activated', 'Subscription Activated'), ('Subscription_Expired', 'Subscription Expired'), ('Subscription_Renewed', 'Subscription Renewed'), ('Account_Suspended', 'Account Suspended'), ('Shipment_Assigned_to_Driver', 'Shipment Assigned to Driver'), ('Welcome_Email', 'Welcome Email'), ('Password_Reset_Requested', 'Password Reset Requested'), ('Payment_Failed', 'Payment Failed'), ('Support_Ticket_Created', 'Support Ticket Created'), ('Support_Ticket_Replied', 'Support Ticket Replied')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pushnotification',
            name='linked_event',
            field=models.CharField(blank=True, choices=[('OTP_Requested', 'OTP Requested'), ('Password_Changed', 'Password Changed'), ('Invoice_Paid', 'Invoice Paid'), ('Subscription_Activated', 'Subscription Activated'), ('Subscription_Expired', 'Subscription Expired'), ('Subscription_Renewed', 'Subscription Renewed'), ('Account_Suspended', 'Account Suspended'), ('Shipment_Assigned_to_Driver', 'Shipment Assigned to Driver'), ('Welcome_Email', 'Welcome Email'), ('Password_Reset_Requested', 'Password Reset Requested'), ('Payment_Failed', 'Payment Failed'), ('Support_Ticket_Created', 'Support Ticket Created'), ('Support_Ticket_Replied', 'Support Ticket Replied')], max_length=50, null=True),
        ),
    ]
