# Generated by Django 5.0 on 2026-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0035_alter_eventmapping_system_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='allow_cross_currency_payments',
            field=models.BooleanField(default=False, help_text='If enabled, this bank account may be shown for invoices in other currencies and the payable amount is converted using internal FX.'),
        ),
    ]
