# Generated by Django 5.0 on 2026-05-12 12:09

import superadmin.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0036_bankaccount_allow_cross_currency_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketreply',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=superadmin.models.ticket_reply_attachment_upload_to),
        ),
    ]
