"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from decouple import config
from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='').split(',')

ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "https://*.ngrok.io",
    "https://*.trycloudflare.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

# Allow SSL termination at proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition (django-tenants: shared = public schema, tenant = per subscriber)
# https://django-tenants.readthedocs.io/

SHARED_APPS = [
    'django_tenants',
    'iroad_tenants',
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'django_celery_results',
    'django_celery_beat',
    'superadmin',
    'rest_framework',
    'corsheaders',
    'mobile_api',
    'iroad_frontend',

]

TENANT_APPS = [
    'tenant_workspace',
    'mobile_api',
]

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

TENANT_MODEL = 'iroad_tenants.TenantRegistry'
TENANT_DOMAIN_MODEL = 'iroad_tenants.TenantSite'

# Hostname may not match a Domain (e.g. localhost CP); keep public schema.
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django_tenants.middleware.main.TenantMainMiddleware',
    'superadmin.middleware.TenantApiSchemaMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    # After Auth (and Message) so flash messages on timeout redirect persist.
    'superadmin.middleware.SessionTimeoutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'superadmin.context_processors.internal_alert_notifications',
                'iroad_tenants.context_processors.tenant_system_banners',
                'iroad_tenants.context_processors.tenant_web_push_config',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# PgBouncer notes (production):
# - Keep this block disabled in local/dev by default.
# - When enabled, point DB_HOST/DB_PORT to PgBouncer endpoint (not direct Postgres).
# - Recommended pool mode for Django is usually "transaction" at PgBouncer level.
# - If using PgBouncer transaction pooling, disable server-side cursors in Django.
#
# Example .env values for PgBouncer deployment:
# DB_HOST=pgbouncer.internal
# DB_PORT=6432
#
# Optional Django-side safety for PgBouncer transaction pooling:
# DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
#
# Optional connection lifetime tuning (helps stale-connection recovery):
# DATABASES['default']['CONN_MAX_AGE'] = config('DB_CONN_MAX_AGE', default=60, cast=int)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static Files
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Login settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

AUTH_USER_MODEL = 'superadmin.AdminUser'

# Email Configuration (SMTP). Tenant API bridge welcome/rotation emails use this
# backend only—see superadmin.communication_helpers.send_email_via_django_smtp.
EMAIL_BACKEND = 'superadmin.email_backend.DatabaseEmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Iroad Admin <sohamghayal02@gmail.com>')

# Redis
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/0')

# Celery
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/1')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/2')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Riyadh'
CELERY_TASK_TRACK_STARTED = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'archive-old-comm-logs-daily': {
        'task': 'iroad.communication.archive_old_comm_logs',
        'schedule': crontab(hour=2, minute=0),
        'args': (90,),
    },
}

# Push notifications (FCM legacy HTTP)
FCM_SERVER_KEY = config('FCM_SERVER_KEY', default='')
FCM_SEND_URL = config('FCM_SEND_URL', default='https://fcm.googleapis.com/fcm/send')
FCM_WEB_VAPID_KEY = config('FCM_WEB_VAPID_KEY', default='')
FIREBASE_WEB_API_KEY = config('FIREBASE_WEB_API_KEY', default='')
FIREBASE_WEB_AUTH_DOMAIN = config('FIREBASE_WEB_AUTH_DOMAIN', default='')
FIREBASE_WEB_PROJECT_ID = config('FIREBASE_WEB_PROJECT_ID', default='')
FIREBASE_WEB_STORAGE_BUCKET = config('FIREBASE_WEB_STORAGE_BUCKET', default='')
FIREBASE_WEB_MESSAGING_SENDER_ID = config('FIREBASE_WEB_MESSAGING_SENDER_ID', default='')
FIREBASE_WEB_APP_ID = config('FIREBASE_WEB_APP_ID', default='')

# Tenant API bridge (CP Type B): require X-Tenant-API-Key by default.
# Set TENANT_API_REQUIRE_KEY=False only for local/dev while migrating clients.
TENANT_API_REQUIRE_KEY = config('TENANT_API_REQUIRE_KEY', default=True, cast=bool)

# Tenant workspace JWTs (bootstrap login, CP impersonation). Defaults to SECRET_KEY.
TENANT_JWT_SIGNING_KEY = config('TENANT_JWT_SIGNING_KEY', default='')

# Optional: shown as primary button in subscriber welcome email.
TENANT_PORTAL_LOGIN_URL = config('TENANT_PORTAL_LOGIN_URL', default='')

# Optional: after CP "Login As", browser is sent here with ?cp_impersonation_token=…
TENANT_IMPERSONATION_REDIRECT_URL = config(
    'TENANT_IMPERSONATION_REDIRECT_URL',
    default='',
)

# Bootstrap POST /api/v1/tenant/auth/bootstrap/ access_token lifetime (seconds).
TENANT_BOOTSTRAP_JWT_TTL_SECONDS = config(
    'TENANT_BOOTSTRAP_JWT_TTL_SECONDS',
    default=900,
    cast=int,
)

# Optional MaxMind GeoLite2-Country.mmdb path for tax routing by client IP (P9).
GEOIP2_COUNTRY_DB = config('GEOIP2_COUNTRY_DB', default='')

# Days after subscription_expiry_date before auto-suspend (billing cron).
SUBSCRIPTION_EXPIRY_GRACE_DAYS = config(
    'SUBSCRIPTION_EXPIRY_GRACE_DAYS',
    default=14,
    cast=int,
)

# Session — keep Django session for JTI pointer only
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24hrs max — Redis TTL controls real expiry

# ─────────────────────────────────────────
# Mobile API — Django REST Framework
# ─────────────────────────────────────────
REST_FRAMEWORK = {
    # Rendering
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],

    # Auth — handled by our custom class
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'mobile_api.authentication.MobileJWTAuthentication',
    ],

    # Permissions — default deny all, override per view
    'DEFAULT_PERMISSION_CLASSES': [
        'mobile_api.permissions.IsMobileAuthenticated',
    ],

    # Pagination — custom envelope
    'DEFAULT_PAGINATION_CLASS':
        'mobile_api.pagination.MobileApiPagination',
    'PAGE_SIZE': 10,

    # Exception handler — custom envelope
    'EXCEPTION_HANDLER':
        'mobile_api.exceptions.mobile_exception_handler',

    # Throttling — rate limiting
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '100/minute',
        'mobile_auth': '10/minute',
        'mobile_otp': '5/minute',
    },
}

# ─────────────────────────────────────────
# Mobile API — CORS Settings
# ─────────────────────────────────────────
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'x-requested-with',
    'x-language',
    'x-tenant-id',
    'x-api-key',
]

# ─────────────────────────────────────────
# Mobile API — JWT Settings
# ─────────────────────────────────────────
MOBILE_API_ACCESS_TOKEN_TTL_SECONDS = config(
    'MOBILE_API_ACCESS_TOKEN_TTL_SECONDS',
    default=3600,
    cast=int,
)
MOBILE_API_REFRESH_TOKEN_TTL_SECONDS = config(
    'MOBILE_API_REFRESH_TOKEN_TTL_SECONDS',
    default=2592000,  # 30 days
    cast=int,
)
MOBILE_API_JWT_SIGNING_KEY = config(
    'MOBILE_API_JWT_SIGNING_KEY',
    default='',
)

# ─────────────────────────────────────────
# Mobile API — Pagination
# ─────────────────────────────────────────
MOBILE_API_DEFAULT_PAGE_SIZE = 10
MOBILE_API_MAX_PAGE_SIZE = 100

