"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from urllib.parse import urlparse

from decouple import config
from pathlib import Path
from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

# Branded 400/403/404/500 pages (designer layout). On by default in all environments.
# Set USE_CUSTOM_ERROR_PAGES=False in .env to restore Django yellow debug pages.
USE_CUSTOM_ERROR_PAGES = config(
    'USE_CUSTOM_ERROR_PAGES',
    default=True,
    cast=bool,
)

# ALLOWED_HOSTS: comma-separated; use explicit hostnames in production (never '*').
# Leading dot = subdomain wildcard (e.g. `.trycloudflare.com` → any `*.trycloudflare.com`).
_allowed_hosts_raw = config('ALLOWED_HOSTS', default='*', cast=str).strip()
ALLOWED_HOSTS = [h.strip() for h in _allowed_hosts_raw.split(',') if h.strip()] or ['*']
CSRF_TRUSTED_ORIGINS = [
    "https://*.ngrok-free.app",
    "https://*.ngrok.io",
    "https://*.trycloudflare.com",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
]

# Optional: current cloudflared/ngrok URL (changes when you restart the tunnel).
# Set DEV_TUNNEL_URL in .env — host/origin are merged into ALLOWED_HOSTS / CSRF / CORS.
_dev_tunnel_url = config('DEV_TUNNEL_URL', default='', cast=str).strip().rstrip('/')
_tunnel_origin = ''
if _dev_tunnel_url:
    _tunnel_parsed = urlparse(_dev_tunnel_url)
    _tunnel_host = (_tunnel_parsed.netloc or '').split('@')[-1].strip()
    if _tunnel_host and _tunnel_host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_tunnel_host)
    if _tunnel_parsed.scheme and _tunnel_host:
        _tunnel_origin = f'{_tunnel_parsed.scheme}://{_tunnel_host}'
    if _tunnel_origin and _tunnel_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_tunnel_origin)

if DEBUG:
    for _dev_host in ('.trycloudflare.com', '.ngrok-free.app', '.ngrok.io'):
        if _dev_host not in ALLOWED_HOSTS:
            ALLOWED_HOSTS.append(_dev_host)

# Allow SSL termination at proxy
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# HTTPS / browser cookie hardening (defaults follow DEBUG: strict when DEBUG=False)
SECURE_SSL_REDIRECT = config('SECURE_SSL_REDIRECT', default=not DEBUG, cast=bool)
SESSION_COOKIE_SECURE = config('SESSION_COOKIE_SECURE', default=not DEBUG, cast=bool)
CSRF_COOKIE_SECURE = config('CSRF_COOKIE_SECURE', default=not DEBUG, cast=bool)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = config('SESSION_COOKIE_SAMESITE', default='Lax', cast=str)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True
X_FRAME_OPTIONS = 'DENY'
SECURE_HSTS_SECONDS = config(
    'SECURE_HSTS_SECONDS',
    default=(31536000 if not DEBUG else 0),
    cast=int,
)
SECURE_HSTS_INCLUDE_SUBDOMAINS = config(
    'SECURE_HSTS_INCLUDE_SUBDOMAINS',
    default=False,
    cast=bool,
)
SECURE_HSTS_PRELOAD = config(
    'SECURE_HSTS_PRELOAD',
    default=False,
    cast=bool,
)
SECURE_REFERRER_POLICY = config(
    'SECURE_REFERRER_POLICY',
    default='same-origin',
    cast=str,
).strip() or 'same-origin'
SECURE_CROSS_ORIGIN_OPENER_POLICY = config(
    'SECURE_CROSS_ORIGIN_OPENER_POLICY',
    default='same-origin',
    cast=str,
).strip() or 'same-origin'

# Application definition (django-tenants: shared = public schema, tenant = per subscriber)
# https://django-tenants.readthedocs.io/

SHARED_APPS = [
    'django_tenants',
    'iroad_tenants',
    'django.contrib.contenttypes',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.admin',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'django_celery_results',
    'django_celery_beat',
    'superadmin',
    'rest_framework',
    'corsheaders',
    'mobile_api',
    'iroad_frontend',

]

TENANT_APPS = [
    'tenant_workspace',
    'mobile_api',
]

INSTALLED_APPS = list(SHARED_APPS) + [
    app for app in TENANT_APPS if app not in SHARED_APPS
]

TENANT_MODEL = 'iroad_tenants.TenantRegistry'
TENANT_DOMAIN_MODEL = 'iroad_tenants.TenantSite'

# Hostname may not match a Domain (e.g. localhost CP); keep public schema.
SHOW_PUBLIC_IF_NO_TENANT_FOUND = True

DATABASE_ROUTERS = ('django_tenants.routers.TenantSyncRouter',)

MIDDLEWARE = [
    'iroad_frontend.middleware.CustomErrorPageMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django_tenants.middleware.main.TenantMainMiddleware',
    'superadmin.middleware.TenantApiSchemaMiddleware',
    'mobile_api.middleware.MobileApiTenantGateMiddleware',
    'mobile_api.middleware.MobileDashboardSecurityMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'mobile_api.middleware.MobileApiSecurityHeadersMiddleware',
    # Serve /static/ when DEBUG=False (see STATICFILES_DIRS); required for styled 404 and marketing pages.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Before tenant gate middleware (uses messages.warning on subscription redirect).
    'django.contrib.messages.middleware.MessageMiddleware',
    'iroad_tenants.middleware.TenantPortalSchemaMiddleware',
    'iroad_tenants.middleware.TenantSubscriptionGateMiddleware',
    # After Auth (and Message) so flash messages on timeout redirect persist.
    'superadmin.middleware.SessionTimeoutMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.template.context_processors.i18n',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'superadmin.context_processors.internal_alert_notifications',
                'iroad_tenants.context_processors.tenant_system_banners',
                'iroad_tenants.context_processors.tenant_web_push_config',
                'iroad_tenants.context_processors.tenant_dashboard_search_routes',
                'iroad_tenants.context_processors.tenant_in_app_notifications',
            ],
            # Explicit path so {% load cms_locale %} works even if auto-discovery
            # of app templatetags packages fails (e.g. import/shadowing issues).
            'libraries': {
                'cms_locale': 'iroad_frontend.templatetags.cms_locale',
                'i18n_fields': 'superadmin.templatetags.i18n_fields',
            },
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# PgBouncer notes (production):
# - Keep this block disabled in local/dev by default.
# - When enabled, point DB_HOST/DB_PORT to PgBouncer endpoint (not direct Postgres).
# - Recommended pool mode for Django is usually "transaction" at PgBouncer level.
# - If using PgBouncer transaction pooling, disable server-side cursors in Django.
#
# Example .env values for PgBouncer deployment:
# DB_HOST=pgbouncer.internal
# DB_PORT=6432
#
# Optional Django-side safety for PgBouncer transaction pooling:
# DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
#
# Optional connection lifetime tuning (helps stale-connection recovery):
# DATABASES['default']['CONN_MAX_AGE'] = config('DB_CONN_MAX_AGE', default=60, cast=int)


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'
LANGUAGES = [
    ('en', 'English'),
    ('ar', 'Arabic'),
]
LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static Files
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

# WhiteNoise: with DEBUG=False, Django does not serve staticfiles; use finders so dev/local
# works without running collectstatic (production should still run collectstatic for caching).
WHITENOISE_USE_FINDERS = True

# Media Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Login settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'

AUTH_USER_MODEL = 'superadmin.AdminUser'

# Email Configuration (SMTP). Tenant API bridge welcome/rotation emails use this
# backend only—see superadmin.communication_helpers.send_email_via_django_smtp.
EMAIL_BACKEND = 'superadmin.email_backend.DatabaseEmailBackend'
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='Iroad Admin <sohamghayal02@gmail.com>')

# Redis
REDIS_URL = config('REDIS_URL', default='redis://127.0.0.1:6379/0')

# Celery
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://127.0.0.1:6379/1')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://127.0.0.1:6379/2')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Asia/Riyadh'
CELERY_TASK_TRACK_STARTED = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_BEAT_SCHEDULE = {
    'archive-old-comm-logs-daily': {
        'task': 'iroad.communication.archive_old_comm_logs',
        'schedule': crontab(hour=2, minute=0),
        'args': (90,),
    },
    'check-subscription-expiry-daily': {
        'task': 'iroad.billing.check_subscription_expiry',
        'schedule': crontab(hour=1, minute=0),
    },
    'apply-scheduled-downgrades-daily': {
        'task': 'iroad.billing.apply_scheduled_downgrades',
        'schedule': crontab(hour=2, minute=0),
    },
}

# Push notifications (FCM legacy HTTP)
FCM_SERVER_KEY = config('FCM_SERVER_KEY', default='')
FCM_SEND_URL = config('FCM_SEND_URL', default='https://fcm.googleapis.com/fcm/send')
FCM_WEB_VAPID_KEY = config('FCM_WEB_VAPID_KEY', default='')
FIREBASE_WEB_API_KEY = config('FIREBASE_WEB_API_KEY', default='')
FIREBASE_WEB_AUTH_DOMAIN = config('FIREBASE_WEB_AUTH_DOMAIN', default='')
FIREBASE_WEB_PROJECT_ID = config('FIREBASE_WEB_PROJECT_ID', default='')
FIREBASE_WEB_STORAGE_BUCKET = config('FIREBASE_WEB_STORAGE_BUCKET', default='')
FIREBASE_WEB_MESSAGING_SENDER_ID = config('FIREBASE_WEB_MESSAGING_SENDER_ID', default='')
FIREBASE_WEB_APP_ID = config('FIREBASE_WEB_APP_ID', default='')

# Tenant API bridge (CP Type B): require X-Tenant-API-Key by default.
# Set TENANT_API_REQUIRE_KEY=False only for local/dev while migrating clients.
TENANT_API_REQUIRE_KEY = config('TENANT_API_REQUIRE_KEY', default=True, cast=bool)

# Tenant workspace JWTs (bootstrap login, CP impersonation). Defaults to SECRET_KEY.
TENANT_JWT_SIGNING_KEY = config('TENANT_JWT_SIGNING_KEY', default='')

# Optional: shown as primary button in subscriber welcome email.
TENANT_PORTAL_LOGIN_URL = config('TENANT_PORTAL_LOGIN_URL', default='')

# Optional: after CP "Login As", browser is sent here with ?cp_impersonation_token=…
TENANT_IMPERSONATION_REDIRECT_URL = config(
    'TENANT_IMPERSONATION_REDIRECT_URL',
    default='',
)

# Bootstrap POST /api/v1/tenant/auth/bootstrap/ access_token lifetime (seconds).
TENANT_BOOTSTRAP_JWT_TTL_SECONDS = config(
    'TENANT_BOOTSTRAP_JWT_TTL_SECONDS',
    default=900,
    cast=int,
)

# Optional MaxMind GeoLite2-Country.mmdb path for tax routing by client IP (P9).
GEOIP2_COUNTRY_DB = config('GEOIP2_COUNTRY_DB', default='')

# Days after subscription_expiry_date before auto-suspend (billing cron).
SUBSCRIPTION_EXPIRY_GRACE_DAYS = config(
    'SUBSCRIPTION_EXPIRY_GRACE_DAYS',
    default=14,
    cast=int,
)

# Session — keep Django session for JTI pointer only
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 86400  # 24hrs max — Redis TTL controls real expiry

# ─────────────────────────────────────────
# Mobile API — response contract
# ─────────────────────────────────────────
MOBILE_API_CONTRACT_VERSION = config(
    'MOBILE_API_CONTRACT_VERSION',
    default='1.0',
    cast=str,
).strip() or '1.0'

# ─────────────────────────────────────────
# Mobile API — Django REST Framework
# ─────────────────────────────────────────
REST_FRAMEWORK = {
    # Rendering
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],

    # Auth — handled by our custom class
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'mobile_api.authentication.MobileJWTAuthentication',
    ],

    # Permissions — default deny all, override per view
    'DEFAULT_PERMISSION_CLASSES': [
        'mobile_api.permissions.IsMobileAuthenticated',
    ],

    # Pagination — custom envelope
    'DEFAULT_PAGINATION_CLASS':
        'mobile_api.pagination.MobileApiPagination',
    'PAGE_SIZE': 10,

    # Exception handler — custom envelope
    'EXCEPTION_HANDLER':
        'mobile_api.exceptions.mobile_exception_handler',

    # Throttling — rate limiting
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '30/minute',
        'user': '100/minute',
        'mobile_auth': '12/minute',
        'mobile_login': '6/minute',
        'mobile_otp': '5/minute',
        'mobile_forgot_password': '5/minute',
        'mobile_verify_otp': '15/minute',
        'mobile_reset_password': '8/minute',
    },
}

# ─────────────────────────────────────────
# Mobile API — CORS Settings
# ─────────────────────────────────────────
# Production: set CORS_ALLOW_ALL_ORIGINS=False and CORS_ALLOWED_ORIGINS to explicit
# https:// origins for any browser-based clients (never use '*' with credentials).
_cors_origins_raw = config('CORS_ALLOWED_ORIGINS', default='', cast=str).strip()
CORS_ALLOWED_ORIGINS = [o.strip() for o in _cors_origins_raw.split(',') if o.strip()]

CORS_ALLOW_ALL_ORIGINS = config(
    'CORS_ALLOW_ALL_ORIGINS',
    default=bool(DEBUG),
    cast=bool,
)
# Typical local web dev (Expo / React) — only when DEBUG is True.
if DEBUG:
    for _origin in (
        'http://127.0.0.1:3000',
        'http://localhost:3000',
        'http://127.0.0.1:8081',
        'http://localhost:8081',
        'http://127.0.0.1:19006',
        'http://localhost:19006',
    ):
        if _origin not in CORS_ALLOWED_ORIGINS:
            CORS_ALLOWED_ORIGINS.append(_origin)
    if _tunnel_origin and _tunnel_origin not in CORS_ALLOWED_ORIGINS:
        CORS_ALLOWED_ORIGINS.append(_tunnel_origin)

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'origin',
    'x-requested-with',
    'x-language',
    'x-tenant-id',
    'x-api-key',
]

# ─────────────────────────────────────────
# Mobile API — JWT Settings
# ─────────────────────────────────────────
MOBILE_API_ACCESS_TOKEN_TTL_SECONDS = config(
    'MOBILE_API_ACCESS_TOKEN_TTL_SECONDS',
    default=3600,
    cast=int,
)
MOBILE_API_REFRESH_TOKEN_TTL_SECONDS = config(
    'MOBILE_API_REFRESH_TOKEN_TTL_SECONDS',
    default=2592000,  # 30 days
    cast=int,
)
MOBILE_API_JWT_SIGNING_KEY = config(
    'MOBILE_API_JWT_SIGNING_KEY',
    default='',
)
# Minimum length for MOBILE_API_JWT_SIGNING_KEY when DEBUG is False (see mobile_api.checks).
MOBILE_API_JWT_SIGNING_KEY_MIN_LENGTH = config(
    'MOBILE_API_JWT_SIGNING_KEY_MIN_LENGTH',
    default=32,
    cast=int,
)
# JWT issuer / audience — embedded in mobile tokens; verified when present on decode.
MOBILE_API_JWT_ISS = config('MOBILE_API_JWT_ISS', default='', cast=str).strip()
MOBILE_API_JWT_AUD = config('MOBILE_API_JWT_AUD', default='', cast=str).strip()
# Small leeway for access/refresh verification (client clock skew vs strict exp).
MOBILE_API_JWT_LEEWAY_SECONDS = config(
    'MOBILE_API_JWT_LEEWAY_SECONDS',
    default=30,
    cast=int,
)
# Require ``iat`` claim on decode (tokens issued by this app always include it).
MOBILE_API_JWT_REQUIRE_IAT_CLAIM = config(
    'MOBILE_API_JWT_REQUIRE_IAT_CLAIM',
    default=not DEBUG,
    cast=bool,
)

# Driver login lockout (per TenantUser row). Set lockout minutes to 0 to disable time window
# (only max attempts applies until successful login resets the counter).
MOBILE_API_LOGIN_MAX_ATTEMPTS = config(
    'MOBILE_API_LOGIN_MAX_ATTEMPTS',
    default=10,
    cast=int,
)
MOBILE_API_LOGIN_LOCKOUT_MINUTES = config(
    'MOBILE_API_LOGIN_LOCKOUT_MINUTES',
    default=15,
    cast=int,
)

# Refresh rotation: ``try_consume_refresh_jti_once`` uses Redis SET NX. When True and
# Redis is unavailable, refresh returns failure instead of fail-open.
MOBILE_API_REFRESH_REQUIRE_REDIS = config(
    'MOBILE_API_REFRESH_REQUIRE_REDIS',
    default=not DEBUG,
    cast=bool,
)

# JWT blacklist writes: transient Redis errors are retried this many times.
MOBILE_API_BLACKLIST_WRITE_RETRIES = config(
    'MOBILE_API_BLACKLIST_WRITE_RETRIES',
    default=2,
    cast=int,
)

# When True, Redis GET errors while checking blacklist / family invalidation
# deny the token (fail closed). Defaults to True when DEBUG is False.
MOBILE_API_JWT_DENY_ON_REDIS_READ_ERROR = config(
    'MOBILE_API_JWT_DENY_ON_REDIS_READ_ERROR',
    default=not DEBUG,
    cast=bool,
)

# When True, a Redis exception during refresh ``SET NX`` denies rotation (replay-safe).
# Recommended True in production even if ``MOBILE_API_REFRESH_REQUIRE_REDIS`` is False.
MOBILE_API_REFRESH_CONSUME_FAIL_CLOSED_ON_REDIS_ERROR = config(
    'MOBILE_API_REFRESH_CONSUME_FAIL_CLOSED_ON_REDIS_ERROR',
    default=True,
    cast=bool,
)

# Extra HTTP headers on ``/api/v1/mobile/*`` (see ``MobileApiSecurityHeadersMiddleware``).
MOBILE_API_SECURITY_HEADERS_ENABLED = config(
    'MOBILE_API_SECURITY_HEADERS_ENABLED',
    default=True,
    cast=bool,
)
MOBILE_API_REFERRER_POLICY = config(
    'MOBILE_API_REFERRER_POLICY',
    default='strict-origin-when-cross-origin',
    cast=str,
).strip()
MOBILE_API_PERMISSIONS_POLICY = config(
    'MOBILE_API_PERMISSIONS_POLICY',
    default='camera=(), microphone=(), geolocation=()',
    cast=str,
).strip()

# Login burst limits (Django cache) — see ``mobile_api.helpers.login_throttle``.
MOBILE_API_LOGIN_BURST_WINDOW_SECONDS = config(
    'MOBILE_API_LOGIN_BURST_WINDOW_SECONDS',
    default=900,
    cast=int,
)
MOBILE_API_LOGIN_BURST_MAX_PER_IP = config(
    'MOBILE_API_LOGIN_BURST_MAX_PER_IP',
    default=60,
    cast=int,
)
MOBILE_API_LOGIN_BURST_MAX_PER_EMAIL = config(
    'MOBILE_API_LOGIN_BURST_MAX_PER_EMAIL',
    default=25,
    cast=int,
)
# When True, cache errors while reading login burst counters deny the attempt.
MOBILE_API_LOGIN_BURST_FAIL_CLOSED_ON_CACHE_ERROR = config(
    'MOBILE_API_LOGIN_BURST_FAIL_CLOSED_ON_CACHE_ERROR',
    default=not DEBUG,
    cast=bool,
)

# Driver home dashboard (recent activity row cap; keep low for mobile latency).
MOBILE_API_DASHBOARD_RECENT_ACTIVITY_LIMIT = config(
    'MOBILE_API_DASHBOARD_RECENT_ACTIVITY_LIMIT',
    default=10,
    cast=int,
)
MOBILE_API_DASHBOARD_SUMMARY_RECENT_ACTIVITY_LIMIT = config(
    'MOBILE_API_DASHBOARD_SUMMARY_RECENT_ACTIVITY_LIMIT',
    default=5,
    cast=int,
)
# Notification summary (inbox + push receipts + ephemeral operational hints).
MOBILE_API_DASHBOARD_NOTIFICATION_ITEMS_LIMIT = config(
    'MOBILE_API_DASHBOARD_NOTIFICATION_ITEMS_LIMIT',
    default=8,
    cast=int,
)
MOBILE_API_DASHBOARD_NOTIFICATION_SUMMARY_ITEMS_LIMIT = config(
    'MOBILE_API_DASHBOARD_NOTIFICATION_SUMMARY_ITEMS_LIMIT',
    default=5,
    cast=int,
)
MOBILE_API_DASHBOARD_NOTIFICATIONS_PUSH_LOOKBACK_DAYS = config(
    'MOBILE_API_DASHBOARD_NOTIFICATIONS_PUSH_LOOKBACK_DAYS',
    default=14,
    cast=int,
)
MOBILE_API_DASHBOARD_NOTIFICATIONS_USE_PUSH_RECEIPTS = config(
    'MOBILE_API_DASHBOARD_NOTIFICATIONS_USE_PUSH_RECEIPTS',
    default=True,
    cast=bool,
)
# Performance: skip nested DRF re-validation when True (payload built by services).
MOBILE_API_DASHBOARD_FAST_SERIALIZE = config(
    'MOBILE_API_DASHBOARD_FAST_SERIALIZE',
    default=True,
    cast=bool,
)
# Summary poll: skip POD document source query (saves 1 round-trip).
MOBILE_API_DASHBOARD_SUMMARY_SKIP_POD_ACTIVITY = config(
    'MOBILE_API_DASHBOARD_SUMMARY_SKIP_POD_ACTIVITY',
    default=True,
    cast=bool,
)
# Optional Redis cache for full/summary dashboard (0 = disabled; 20s recommended).
MOBILE_API_DASHBOARD_CACHE_TTL_SECONDS = config(
    'MOBILE_API_DASHBOARD_CACHE_TTL_SECONDS',
    default=20,
    cast=int,
)
MOBILE_API_DASHBOARD_SLICE_CACHE_TTL_SECONDS = config(
    'MOBILE_API_DASHBOARD_SLICE_CACHE_TTL_SECONDS',
    default=20,
    cast=int,
)
MOBILE_API_DASHBOARD_MOVEMENT_SCOPE_PK_CAP = config(
    'MOBILE_API_DASHBOARD_MOVEMENT_SCOPE_PK_CAP',
    default=500,
    cast=int,
)
MOBILE_API_DASHBOARD_SLOW_REQUEST_MS = config(
    'MOBILE_API_DASHBOARD_SLOW_REQUEST_MS',
    default=800,
    cast=int,
)
MOBILE_API_DASHBOARD_SHIPMENT_SCOPE_PK_CAP = config(
    'MOBILE_API_DASHBOARD_SHIPMENT_SCOPE_PK_CAP',
    default=500,
    cast=int,
)
# Dashboard security: sanitize outbound IDs; middleware JWT/header tenant binding.
MOBILE_API_DASHBOARD_ENFORCE_OWNERSHIP_SANITIZE = config(
    'MOBILE_API_DASHBOARD_ENFORCE_OWNERSHIP_SANITIZE',
    default=True,
    cast=bool,
)
MOBILE_API_DASHBOARD_MIDDLEWARE_ENFORCE_TENANT = config(
    'MOBILE_API_DASHBOARD_MIDDLEWARE_ENFORCE_TENANT',
    default=True,
    cast=bool,
)

# Mobile driver JWT: require JWT email/driver_id/role_name to match DB when present.
MOBILE_API_JWT_STRICT_CLAIM_BINDING = config(
    'MOBILE_API_JWT_STRICT_CLAIM_BINDING',
    default=True,
    cast=bool,
)

# Optional CSV of allowed ``TenantUser.role_name`` values (case-insensitive) for
# mobile API. When empty, any user with an active linked DriverMaster is allowed.
MOBILE_API_DRIVER_ROLE_ALLOWLIST = config(
    'MOBILE_API_DRIVER_ROLE_ALLOWLIST',
    default='',
    cast=str,
).strip()

# When True, every mobile JWT access/refresh validation requires a resolvable
# tenant hint (X-Tenant-ID and/or request.tenant) that matches token tenant_schema.
MOBILE_API_JWT_REQUIRE_TENANT_HINT = config(
    'MOBILE_API_JWT_REQUIRE_TENANT_HINT',
    default=True,
    cast=bool,
)

# Legacy: password-reset no longer requires X-Tenant-ID (email/OTP discovery).
# Kept for compatibility if re-enabled in custom deployments.
MOBILE_API_AUTH_ENDPOINTS_REQUIRE_TENANT_HINT = config(
    'MOBILE_API_AUTH_ENDPOINTS_REQUIRE_TENANT_HINT',
    default=False,
    cast=bool,
)

# When True, driver login never uses cross-tenant auto-discovery; tenant_id or
# X-Tenant-ID is mandatory. Defaults to True when DEBUG is False.
MOBILE_API_LOGIN_REQUIRE_EXPLICIT_TENANT = config(
    'MOBILE_API_LOGIN_REQUIRE_EXPLICIT_TENANT',
    default=not DEBUG,
    cast=bool,
)

# Password reset: allow legacy email/OTP **cross-tenant schema scan** when no
# tenant hint is provided. **Strongly discouraged** — keep False in production.
MOBILE_API_PASSWORD_RESET_ALLOW_CROSS_TENANT_DISCOVERY = config(
    'MOBILE_API_PASSWORD_RESET_ALLOW_CROSS_TENANT_DISCOVERY',
    default=False,
    cast=bool,
)

# When True, cache errors while reading password-reset rate-limit counters deny
# the request (fail closed). Defaults to True when DEBUG is False.
MOBILE_API_PASSWORD_RESET_RATE_FAIL_CLOSED_ON_CACHE_ERROR = config(
    'MOBILE_API_PASSWORD_RESET_RATE_FAIL_CLOSED_ON_CACHE_ERROR',
    default=not DEBUG,
    cast=bool,
)

# Password reset / OTP (see ``mobile_api.helpers.password_reset_security``)
MOBILE_API_PASSWORD_RESET_OTP_EXPIRY_MINUTES = config(
    'MOBILE_API_PASSWORD_RESET_OTP_EXPIRY_MINUTES',
    default=10,
    cast=int,
)
MOBILE_API_PASSWORD_RESET_OTP_MAX_ATTEMPTS = config(
    'MOBILE_API_PASSWORD_RESET_OTP_MAX_ATTEMPTS',
    default=5,
    cast=int,
)
MOBILE_API_PASSWORD_RESET_RESEND_COOLDOWN_SECONDS = config(
    'MOBILE_API_PASSWORD_RESET_RESEND_COOLDOWN_SECONDS',
    default=90,
    cast=int,
)
MOBILE_API_PASSWORD_RESET_RATE_WINDOW_SECONDS = config(
    'MOBILE_API_PASSWORD_RESET_RATE_WINDOW_SECONDS',
    default=3600,
    cast=int,
)
MOBILE_API_PASSWORD_RESET_FORGOT_EMAIL_MAX_PER_HOUR = config(
    'MOBILE_API_PASSWORD_RESET_FORGOT_EMAIL_MAX_PER_HOUR',
    default=5,
    cast=int,
)
MOBILE_API_PASSWORD_RESET_FORGOT_IP_MAX_PER_HOUR = config(
    'MOBILE_API_PASSWORD_RESET_FORGOT_IP_MAX_PER_HOUR',
    default=25,
    cast=int,
)
MOBILE_API_PASSWORD_RESET_VERIFY_IP_MAX_PER_HOUR = config(
    'MOBILE_API_PASSWORD_RESET_VERIFY_IP_MAX_PER_HOUR',
    default=60,
    cast=int,
)
MOBILE_API_PASSWORD_RESET_VERIFY_EMAIL_MAX_PER_HOUR = config(
    'MOBILE_API_PASSWORD_RESET_VERIFY_EMAIL_MAX_PER_HOUR',
    default=40,
    cast=int,
)
MOBILE_API_PASSWORD_RESET_RESET_IP_MAX_PER_HOUR = config(
    'MOBILE_API_PASSWORD_RESET_RESET_IP_MAX_PER_HOUR',
    default=20,
    cast=int,
)
MOBILE_API_PASSWORD_RESET_TIMING_JITTER_MS = config(
    'MOBILE_API_PASSWORD_RESET_TIMING_JITTER_MS',
    default=35,
    cast=int,
)

# ─────────────────────────────────────────
# Mobile API — RBAC (role groups + capabilities)
# ─────────────────────────────────────────
# CSV of TenantUser.role_name values (case-insensitive) that count as **driver**
# mobile principals when ``driver_id`` is present in the JWT. When blank,
# built-in defaults apply and entries from MOBILE_API_DRIVER_ROLE_ALLOWLIST are unioned.
MOBILE_API_RBAC_DRIVER_ROLE_NAMES = config(
    'MOBILE_API_RBAC_DRIVER_ROLE_NAMES',
    default='',
    cast=str,
).strip()

# CSV for **dispatcher** operational mobile APIs (see ``mobile.operations.*``).
MOBILE_API_RBAC_DISPATCHER_ROLE_NAMES = config(
    'MOBILE_API_RBAC_DISPATCHER_ROLE_NAMES',
    default='',
    cast=str,
).strip()

# CSV for **tenant admin** (JWT ``is_admin`` is also set from this list at login).
MOBILE_API_RBAC_TENANT_ADMIN_ROLE_NAMES = config(
    'MOBILE_API_RBAC_TENANT_ADMIN_ROLE_NAMES',
    default='',
    cast=str,
).strip()

# ─────────────────────────────────────────
# Mobile API — Pagination
# ─────────────────────────────────────────
MOBILE_API_DEFAULT_PAGE_SIZE = 10
MOBILE_API_MAX_PAGE_SIZE = 100

# ─────────────────────────────────────────
# Mobile API — POD capture (durable staging)
# ─────────────────────────────────────────
MOBILE_POD_BUNDLE_TTL_HOURS = config('MOBILE_POD_BUNDLE_TTL_HOURS', default=72, cast=int)
MOBILE_POD_CAPTURE_REQUIRE_SYNC_METADATA = config(
    'MOBILE_POD_CAPTURE_REQUIRE_SYNC_METADATA',
    default=False,
    cast=bool,
)
MOBILE_POD_CAPTURE_REQUIRE_STORAGE_VERIFICATION = config(
    'MOBILE_POD_CAPTURE_REQUIRE_STORAGE_VERIFICATION',
    default=True,
    cast=bool,
)
MOBILE_POD_CAPTURE_ENFORCE_IMMUTABILITY = config(
    'MOBILE_POD_CAPTURE_ENFORCE_IMMUTABILITY',
    default=True,
    cast=bool,
)

MOBILE_POD_CAPTURE_ALLOW_ORPHAN_RETRY = config(
    'MOBILE_POD_CAPTURE_ALLOW_ORPHAN_RETRY',
    default=True,
    cast=bool,
)

