
import os

po_file_path = r"c:\Users\soham\Downloads\codes\iroad_worllog\iroad\locale\ar\LC_MESSAGES\django.po"

# A comprehensive list of translations for this project
translations = {
    "": "Project-Id-Version: iRoad\\nReport-Msgid-Bugs-To: \\nPOT-Creation-Date: 2026-04-20 00:00+0000\\nPO-Revision-Date: 2026-04-20 00:00+0000\\nLanguage: ar\\nMIME-Version: 1.0\\nContent-Type: text/plain; charset=UTF-8\\nContent-Transfer-Encoding: 8bit\\n",
    "Actions": "الإجراءات",
    "Active": "نشط",
    "Active Subscribers": "المشتركين النشطين",
    "Add": "إضافة",
    "Analytics": "التحليلات",
    "Back": "رجوع",
    "Cancel": "إلغاء",
    "Close": "إغلاق",
    "Companies": "الشركات",
    "Company List": "قائمة الشركات",
    "Configuration": "الإعدادات",
    "Dashboard": "لوحة القيادة",
    "Delete": "حذف",
    "Description": "الوصف",
    "Done": "تم",
    "Dropdown Master": "إدارة القوائم",
    "Edit": "تعديل",
    "Email": "البريد الإلكتروني",
    "Email Configuration": "إعدادات البريد",
    "Email Templates": "قوالب البريد",
    "Here's what's happening with your system today": "نظرة عامة على نشاط نظامك اليوم",
    "Inactive": "غير نشط",
    "Languages": "اللغات",
    "My Account": "حسابي",
    "Name": "الاسم",
    "Next": "التالي",
    "No data available": "لا توجد بيانات",
    "No notifications": "لا توجد إشعارات",
    "No records found": "لم يتم العثور على سجلات",
    "Notifications": "الإشعارات",
    "Pending Approvals": "الموافقات المعلقة",
    "Pending Liquidity": "السيولة المعلقة",
    "Previous": "السابق",
    "Reports": "التقارير",
    "Revenue Forecast & Trend": "توقعات الإيرادات والاتجاه",
    "Save": "حفظ",
    "Search shipments, clients, addresses...": "ابحث عن الشحنات والعملاء والعناوين...",
    "Search...": "بحث...",
    "Settings": "الإعدادات",
    "Sign out": "تسجيل الخروج",
    "Status": "الحالة",
    "Subadmin": "مسؤول فرعي",
    "Subscription Packages": "باقات الاشتراك",
    "Subscription Report": "تقرير الاشتراكات",
    "Subscriptions": "الاشتراكات",
    "Super Admin": "المشرف العام",
    "Super Admin Dashboard": "لوحة تحكم المشرف العام",
    "Switch Language": "تبديل اللغة",
    "Ticket Health": "صحة التذاكر",
    "Total Revenue This Month": "إجمالي الإيرادات هذا الشهر",
    "User Management": "إدارة المستخدمين",
    "Welcome back": "مرحباً بعودتك",
    "You are yet to receive notifications": "لم تصلك إشعارات بعد",
    "Administration": "الإدارة",
    "System Users Management": "إدارة مستخدمي النظام",
    "Users Analytics": "تحليلات المستخدمين",
    "Roles Master": "سجل الأدوار",
    "Admin Users": "مستخدمين النظام",
    "Subscription Plans Management": "إدارة باقات الاشتراك",
    "Subscription Plans": "باقات الاشتراك",
    "Add-ons Pricing": "أسعار الإضافات",
    "Promo Codes": "أكواد الخصم",
    "Subscribers CRM & Billing": "إدارة المشتركين والفوترة",
    "Subscribers List": "قائمة المشتركين",
    "Subscription Orders": "طلبات الاشتراك",
    "Transactions Ledger": "سجل المعاملات",
    "Standard Invoices": "الفواتير القياسية",
    "Communication & Alerts": "الاتصالات والتنبيهات",
    "Gateway Settings": "إعدادات البوابات",
    "Notification Templates": "قوالب الإشعارات",
    "Events Mapping": "ربط الأحداث",
    "System Banners": "لافتات النظام",
    "Internal Alerts": "التنبيهات الداخلية",
    "Comm Logs": "سجلات الاتصال",
    "Payment Infrastructure": "البنية التحتية للمدفوعات",
    "Bank Accounts": "الحسابات البنكية",
    "Payment Gateways": "بوابات الدفع",
    "Payment Methods": "طرق الدفع",
    "Global Master Data": "البيانات الأساسية العالمية",
    "Countries Master": "سجل الدول",
    "Currencies Master": "سجل العملات",
    "System Configurations & Tax": "إعدادات النظام والضرائب",
    "Tax Codes": "الأكواد الضريبية",
    "General Tax Settings": "إعدادات الضرائب العامة",
    "Legal Identity": "الهوية القانونية",
    "Global System Rules": "قواعد النظام العالمية",
    "Base Currency": "العملة الأساسية",
    "Exchange Rates": "أسعار الصرف",
    "FX Change Log": "سجل تغيير أسعار الصرف",
    "Support Management": "إدارة الدعم الفني",
    "Support Categories": "فئات الدعم",
    "Canned Responses": "الردود الجاهزة",
    "Support Tickets": "تذاكر الدعم",
    "Security & Audit": "الأمن والتدقيق",
    "Access Log": "سجل الوصول",
    "Admin Security": "أمن المسؤولين",
    "Active Sessions Monitor": "مراقبة الجلسات النشطة",
    "Audit Log": "سجل التدقيق",
    "System Users Analytics": "تحليلات مستخدمي النظام",
    "Staff overview and activity insights": "نظرة عامة على الموظفين ورؤى النشاط",
    "Total Active Staff": "إجمالي الموظفين النشطين",
    "Suspended Accounts": "الحسابات الموقوفة",
    "Pending Activation": "في انتظار التفعيل",
    "2FA Adoption Rate": "معدل اعتماد التحقق الثنائي",
    "Stale Accounts": "الحسابات غير النشطة",
    "Accounts inactive for 30+ days (Active only)": "الحسابات غير النشطة لأكثر من 30 يوماً (النشطة فقط)",
    "Last Login": "آخر تسجيل دخول",
    "Days Since Login": "الأيام منذ آخر دخول",
    "All clear": "الكل نشط",
    "All accounts are active recently": "جميع الحسابات كانت نشطة مؤخراً",
    "Role Distribution": "توزيع الأدوار",
    "Active users per role": "المستخدمون النشطون لكل دور",
    "Role Name": "اسم الدور",
    "User Count": "عدد المستخدمين",
    "Recently Added Users": "المستخدمون المضافون حديثاً",
    "Created At": "تاريخ الإنشاء",
    "Pending": "قيد التفعيل",
    "Suspended": "موقوف",
    "Locked": "مغلق",
    "Queue": "قائمة الانتظار",
    "Adoption": "الاعتماد",
    "Unassigned": "غير معين",
    "Role": "الدور",
    "Admin": "مسؤول",
}

with open(po_file_path, "w", encoding="utf-8") as f:
    for msgid, msgstr in translations.items():
        f.write(f'msgid "{msgid}"\n')
        f.write(f'msgstr "{msgstr}"\n\n')

print("Generated a fresh django.po file.")
